### ISSUE TITLE
Add conjure to neovim wiki

### ISSUE THREAD

**Issue by KillTheMule** [Olical/conjure#1]
Hey, seems your project is coming along well :) I noted you did not add conjure to the page of [related projects](https://github.com/neovim/neovim/wiki/Related-projects) in the neovim wiki. I pondered doing so, but felt this might not be in your best interest... so I just wanted to ask, should I add it? Would you want to do it yourself at some later time?

Cheers!

**Comment by Olical** [comment]
Oh cool, good idea! Thank you for considering my opinion too :smile:

I think I'll hold off for a little while because there's still a couple of core features I'd like to finish as well as the documentation. I'll leave this issue open as a reminder and add it myself (or ask you too?) at a later date. Thanks a lot!

**Comment by Olical** [comment]
Done!
