### ISSUE TITLE
Change color scheme

### ISSUE THREAD

**Issue by optevo** [Olical/conjure#101]
In the output pane in the top right where I see the evaluation results, the output color scheme makes it hard to read the evaluated forms. The background color is purple-ish and the text is pink-ish and delimiters are red so the contrast is awful.

I don't use neovim much and don't really know where to start with configuring the color scheme. I checked ":help conjure" and there didn't seem to be anything on changing colors there so I don't even know if this is something that I need to configure that's specific to your plugin. If you could point me at relevant docs I need to change the colors I'd appreciate it.

Thanks,
Richard

**Comment by Olical** [comment]
Hello! I hope you had a good week and are looking forward to a nice weekend :smile: 

So Conjure doesn't actually have a theme, it relies on whatever your theme defines for the `Pmenu` group (I'm not sure why Neovim decided this should be the group for floating windows, but here we are. Maybe I should see if I can hack it so that it's not `Pmenu` and it's like `ConjureHUDBackground` that defaults to `Pmenu` :thinking: but that's another issue.

There's an answer in the FAQs about this but it's not very obvious at all, maybe I could mention it elsewhere like in the help text: [The HUD window background colour makes the text unreadable, how can I change it?](https://github.com/Olical/conjure/wiki/Frequently-asked-questions#the-hud-window-background-colour-makes-the-text-unreadable-how-can-i-change-it)

Does this help you out for now? I could definitely do with more docs on this issue or maybe even a nicer way for the user to set it. For context, here's how mine looks by default in a 256 colour terminal and a dark theme that picked a light grey for pop up menu (floating window) backgrounds.

![image](https://user-images.githubusercontent.com/315229/85197516-5d3abf80-b2d9-11ea-9b91-cb686a61a98a.png)

**Comment by Olical** [comment]
Oh! I just tried this and it works too!

```vim
:highlight NormalFloat ctermbg=black guibg=black
```

This problem should kind of fade away as more and more themes support things like Vim's pop up window and Neovim's floating window nicely.

**Comment by Olical** [comment]
Going to close this since I'm hopeful that setting will be enough to fix the issue and there shouldn't be anything else that requires changing within Conjure itself. Let me know if you still have questions!
