### ISSUE TITLE
Allow multiple REPL connections based on current working directory

### ISSUE THREAD

**Issue by m00qek** [Olical/conjure#105]
Hi, first of all, thanks a lot for this plugin. It is making me way more productive :)

### Proposal 

Allow `conjure` to have multiple active REPL connections, one per working directory.

### Why?
[Vim](https://github.com/vim/vim/blob/7ff78465f7057a672a6de0d75d56286da253501b/runtime/doc/editing.txt#L1319) and [Neovim](https://github.com/neovim/neovim/blob/ef8f965c64c157de728124a84281630cfb234002/runtime/doc/editing.txt#L1262) support the command `tcd`, which allows the user to change the working directory of a single tab page and all of its windows. A user can take advantage of this to manage multiple projects in the same vim/neovim, each one on a different tab page. 
Some plugins, like [FZF](https://github.com/junegunn/fzf.vim) and [contabs](https://github.com/m00qek/nvim-contabs), base most of their functionalities  (search files, etc.) in the current working dir making this workflow possible.

### Concerns 
I don't know if this will play well with the options `g:conjure#eval#relative_file_root` and `g:conjure#eval#always_absolute_file`.

**Comment by m00qek** [comment]
If this is something that you want in `conjure` I'll be happy to work on a implementation.

**Comment by m00qek** [comment]
I was looking at the code and realized that `conjure` already allows multiple REPLs, one by each filetype. 

One strategy to make this work could be adding a set of "tags" to each `client` and `log` window and allow users to, optionally, declare two functions: one that creates tags, used when a connection is created,  and another that given a list of elements that contain tags chooses one, used to select in which client/log-window conjure will eval an expression.

The default pair of functions (shipped with conjure) could tag clients/log-windows only with the filetype; this way `conjure` will have the same functionality as it has today but with an API for others to build extensions to handle `working directories` and even `remote/local` connections :)

**Comment by Olical** [comment]
I haven't had the time to think this through and respond properly yet, I will! But I wanted to say that the concern about the relative path code shouldn't be too bad, I've switched it off by default in the next version (see `develop` after some trial in the wild and merged the two options into one. So now you just set `g:conjure#relative_file_root` if you _need_ relative file paths relative to any directory. Just thought that'd be good to know!

And yeah, Conjure is semi language agnostic (very lisp leaning right now), but those language clients each have their own ways to deal with connections, I leave it up to the implementation. My only worry is that this functionality would complicate different clients in different ways and some could be inconsistent if they couldn't provide this behaviour.

I'm thinking if clients could be instantiated multiple times it could get around this without clients having to know about the feature :thinking: alternatively, all clients could just use the CWD in all lookups of current connection state as a convention.

Another approach: Clients don't store state within their modules, they request their state via a function from the `conjure.client` module (or similar), that could (by default) just return a table for them to use and mutate. Then the functionality of a table per CWD (or even other rules! Maybe they could be saved and restored!) could be implemented in a way that's hidden from the client.

I _think_ every client I've implemented so far has ended up with a `state` table that I store the current connection and in-flight requests in. I _think_ moving the state implementation out into something clients hook into externally could give us this feature easily (in a way that can be turned off if desired (maybe per client)) as well as other fancy future connection / state behaviour.

**Comment by Olical** [comment]
That's the thing with Conjure, since I want it to be a nexus of REPL tooling from different languages, I need to find solutions and concepts that all can benefit from :smile: this gives us a fulcrum, improve one thing to improve N different tools for _very_ niche languages that tend to be neglected tooling-wise. The only way to get these smaller language communities cool tools is to share the work of others :blush:

**Comment by m00qek** [comment]
> alternatively, all clients could just use the CWD in all lookups of current connection state as a convention

this would solve _my_ problem, but won't make `conjure` more extensible... and the implementation will need to handle multiple "states" anyway, which seems the hardest thing to do

> Clients don't store state within their modules, they request their state via a function from the conjure.client module (or similar), that could (by default) just return a table for them to use and mutate.

This would be really good. If a connection is represented by a state table, clients would be just a group of functions that receive that state and mutate it. 
Seems like a big change, though. The nrepl client has some occurrences of `def` and `defonce` that store mutable data and are referred directly by other namespaces.

**Comment by Olical** [comment]
It's not so bad really, I think I'll just refactor the clients to pull their state from a table stored in `conjure.client` via a function. nREPL already defines a state module, this would just move that concept to a system used by all other clients.

I'll do that state move refactor and see how it looks today I think, that change is good in its own right. Then adding CWD splitting the state is just a case of changing that one `get-state` function :)

**Comment by Olical** [comment]
So that commit referenced above seems to work well. I just need to do it for Fennel and Janet too, but that should be easier to be honest.

The only thing I haven't really thought about is how to divide logs up through arbitrary means too. Maybe that can be something the Conjure system as a whole helps with by setting something in the client state too :thinking: also I'm currently passing keys to `conjure.client/state` to access the client state I want. I might make that automatic, it just requires the current client to always be set... which is _should_ be?

Some async things that aren't invoked by the user (i.e. results from evals) can come back while the user is in another filetype so I use a sort of dynamic variable (not actually dynamic, my own thing) that forces this filetype for a call stack.

**Comment by m00qek** [comment]
Wow, that was fast :)
Is the goal of this commit just to move the state from each client to `conjure.client`? 

I was expecting `conjure.client/client-states` to be just a vector more or less like
```clojure
[{:conn nil
  :tag  {:filetype :clojure :client :nrepl}
  ... }
{:conn nil
  :tag  {:filetype :fennel :client :aniseed}
  ... }]
```  
that way you can have more REPLs of the same filetype by adding another key/pair to `:tag`.

> Some async things that aren't invoked by the user (i.e. results from evals) can come back while the user is in another filetype so I use a sort of dynamic variable (not actually dynamic, my own thing) that forces this filetype for a call stack.

Can't you just pass some info to identify the client (via closure) when you trigger the action?

**Comment by Olical** [comment]
For now, I'm just moving everything to that central point gated by a function where I can insert more keys (such as the CWD at the time of invocation). I would like a nested tree of data over a vector to avoid having to search, the data should be indexed in this one way (cwd -> client -> sub-keys) until another indexing method is required.

One path that worries me with this:

 * User starts long running eval (think 10 seconds).
 * User navigates to another tab in another CWD.
 * Result comes back from the REPL, client asks for current state.
 * `conjure.client` returns the current state of _another_ CWD which contains another connection.

The only way around this is to hold a reference to the original state / config _or_ have a similar mechanism of `with-filetype` but `with-cwd` to ensure the CWD is preserved across callbacks. Perhaps I can include a `with-env` instead which carries the filetype _and_ CWD (as well as anything else required) through to the callback when it's invoked :thinking:

> Can't you just pass some info to identify the client (via closure) when you trigger the action?

Yes, but that information then needs to flow through to every function that could possibly reference a function in `conjure.log` somewhere down the call stack. Think `*dynamic*` values in Clojure and `binding`, I'm simulating that through state so I'm setting something akin to `(binding [*filetype* clojure] ...)` in callbacks.

I think I could do with something that carries the current Client _and_ CWD (+ any other factors) through to callbacks.

**Comment by m00qek** [comment]
> For now, I'm just moving everything to that central point gated by a function where I can insert more keys (such as the CWD at the time of invocation). I would like a nested tree of data over a vector to avoid having to search, the data should be indexed in this one way (cwd -> client -> sub-keys) until another indexing method is required.

Got it. I wasn't concerned about a search because it is unlikely to this list to get big (is anyone out there planning to have hundreds of active connections?)

>  Yes, but that information then needs to flow through to every function that could possibly reference a function in conjure.log somewhere down the call stack. Think *dynamic* values in Clojure and binding, I'm simulating that through state so I'm setting something akin to (binding [*filetype* clojure] ...) in callbacks.

I guess I don't mind carrying values around, seems easier to handle async. But if you go with the "binding" idea, `with-env` seems a better approach to allow more data in the future :)

**Comment by Olical** [comment]
Yeah, I'm thinking a with-env that takes a filetype (or reuses) and is intended to create callbacks that simulate the CWD and filetype of your current buffer at the time of the invocation. I have a few functions that rely on this global information just to keep clients kind of worry free to an extent? I may well rethink it at some point, but for now it's minimal pain for slightly "it just works" APIs I guess. Maybe not worth it! I'll carry on tinkering soon, shutting down for the night :smile:

**Comment by Olical** [comment]
Thinking about multiple logs:

 * I could have a log per [some distinguishing factor or combinations of factors]
 * I already have a log per client
 * If you're in CWD X and then a result comes back from CWD Y, do you display the HUD of Y on your X tab?
 * If you display another CWDs HUD in a different tab then open the log, you'll get the current tab's log. Confusing!

I think the best bet is multiple client states for multiple connections, one log and HUD. I think having N logs for N clients is just too much for the user (and my own modelling) to handle. I want to subtly augment the current experience, not alter the meaning of certain things (the HUD appearing wherever you are so you know the thing finished) entirely.

So yeah, I _think_ there should only be one log per client, regardless of how many client states you're creating, the log system is separate to that and more of a global concept. Just explaining my reasoning for this, the log and HUD are pretty integral to the UX (if not the main defining feature of Conjure) and I don't want to complicate them.

**Comment by m00qek** [comment]
> I think the best bet is multiple client states for multiple connections, one log and HUD
I guess that could work if there is some indication, in the log entry, of what connection generated it - this is important because of long, async, evals.

**Comment by Olical** [comment]
Still making progress on this but nothing to try yet, basically more refactoring and cleaning which is good in it's own right. Making positive changes that accidentally make this _really_ easy to add, my favourite kind of development :smile: 

I'm still [hammock timing](https://www.youtube.com/watch?v=f84n5oFoZBc&list=PLlvl8W3flzkcuwBbpUXdWQLRBibF9kK5o&index=2) on UX since that's arguably the most important part while also being the hardest to ever change. I'm leaning towards implementing it in a semi-hidden way first (no automatic switching, you can set up autocmds to call a thing which switches your client state over to another key). This could be released and battle tested while I improved other things.

If that exposed low level plumbing can work well with some user side autocmds or whatever I'll add some high level UX levers (such as hooking into tab change or mappings) to drive it for you.

I agree that there should be something in the log when you have multiple states, I'll bake that concept into this "switch client state behaviour". That's how I really see this feature, it's the ability to switch out a client's state at any time which brings a new connection with it. The whole "tabs with different connections" concept is really a specialisation of this more general feature, if that makes sense?

No need to respond here unless something catches your eye, just logging my thoughts as I go along for future me / other people.

**Comment by Olical** [comment]
I have this working for all clients :slightly_smiling_face:

```
:lua require('conjure.client')['set-state-key!']('anything-i-want-to-use-as-a-key')
```

Now swapping between that and `default` will swap states in any client. I need to fix one thing around closing all connections on exit, but it's coming along nicely! I have changed a LOT of code, so I hope it's all still okay...

**Comment by Olical** [comment]
Done! To an extent! :tada: so I haven't added an opinionated UX yet (may never?), I've just finished the tools you need to do this seamlessly in any Conjure client (yes, any, not just Clojure!). You'll have to translate this from Fennel but I just tested this and it only bloody works. I can work on two projects at once in two tabs :smile:

```
(nvim.ex.augroup :conjure_set_state_key_on_dir_changed)
(nvim.ex.autocmd_)
(nvim.ex.autocmd
  "DirChanged * call luaeval(\"require('conjure.client')['set-state-key!']('\" . getcwd() . \"')\")")
(nvim.ex.augroup :END)
```

You could do this for _any_ unique string, not just a path, but it works pretty well. The log will then tell you which project the evals came from, even if there's a delay... in theory. I'm yet to prove that but it should be fine :slightly_smiling_face: 

Let me know what you think! I've ended up refactoring and tidying up so many internals to get this to work, really happy with how it turned out!

**Comment by Olical** [comment]
```
augroup conjure_set_state_key_on_dir_changed
  autocmd!
  autocmd DirChanged * execute "ConjureClientState " . getcwd()
augroup END
```

Slightly neater with the new `ConjureClientState` command :smile:

**Comment by Olical** [comment]
I'm going to close this since you can do it now :smile: (let me know if you hit any issues!)
