### ISSUE TITLE
How to enable autocompletion for ClojureScript?

### ISSUE THREAD

**Issue by gleisonsilva** [Olical/conjure#108]
Hello! I've installed Deoplete and it's working when edition Javascript, CSS, etc.. but it's not for ClojureScript... I do need to add something to my deps to get this working? I'm using Shadow-cljs
Thank you very much for your amazing work!

**Comment by Olical** [comment]
Hey! This is probably the issue someone else ran into! clj-suitable was broken for shadow-cljs recently, there's an option on the `develop` branch to disable the enhanced CLJS completion and just rely on the core completion mechanics: `let g:conjure#client#clojure#nrepl#completion#cljs#use_suitable = v:false` on develop should do it? As long as you have the CIDER middleware too? https://github.com/Olical/conjure/wiki/Quick-start:-ClojureScript-(shadow-cljs)

**Comment by Olical** [comment]
#107 details the issues with advanced CLJS completion, I think just swapping to the develop branch will get it working for you.

**Comment by Olical** [comment]
I'm going to close this for now since I _think_ it's probably to do with this upstream bug which there's currently a workaround for in the latest release https://github.com/Olical/conjure/pull/107

Hopefully it'll get fixed soon! Until then this slightly simpler completion should be working now. Let me know if not!
