### ISSUE TITLE
Formatting code

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#11]
Since I can include something like [zprint](https://github.com/kkinnear/zprint) inside Conjure it'll mean we can run code through that within Conjure's JVM to format it. How neat! Not sure if I'll definitely use zprint yet but it's a good candidate.

**Comment by Olical** [comment]
Not going to do this just yet, will close. Not a primary concern and there's other better CLI tools floating about. I don't want to commit to a tool before the community decides. There's ongoing work to decide what standard people should use and how it should be enforced.

**Comment by stopachka** [comment]
Popping in here, to summarize a recent discussion on Slack. 

### Option A: call cljfmt directly from vim

One quick way to format code right now, is by using cljfmt like so

```
 * in vimrc nmap <leader>f :!clj -M:cljfmt %<CR>
 * in deps.edn {:aliases {:cljfmt {:extra-deps {cljfmt/cljfmt {:mvn/version "0.7.0"}} :main-opts ["-m" "cljfmt.main" "fix"]}}} 
```

### Option B: Use clojure-lsp 

If you use coc + clojure-lsp, you can get code-formatting out of the box. See this guide for adding it: https://clojure-lsp.github.io/clojure-lsp/clients/#vim

### Option C: Add support for code-formatting in Conjure

CIDER already uses nREPL. From Olical: 

"""
I want to add support for the newer nREPL 0.8 operations + refactor/debug/format tools in CIDER (when they're present) but time. If anyone wants to have a go at contributing these things (wouldn't be too hard for some of them!) I'd be happy to review / guide / carry PRs across the line

There's a LOT of untapped power in CIDER right now, low hanging fruit in some cases. Although things like a stepping debugger (anything stateful) will require some UI / UX work that I'll try to handle since I have a bigger view of the system.


Formatting should be a case of
 * extract form under cursor
 * send off to CIDER
 * replace form range with result

All of which have prior art in Conjure and Fennel modules / functions dedicated to performing this extraction / replacement in a buffer. It's how <prefix>e! works after all.

I actually format data sometimes by just running <prefix>e! on it since the source data gets replaced by a pretty printed version

My personal motivation for formatting is quite low since I've never relied on one for Clojure in years of professional development with it. No single formatting tool ever sat with me as "perfect", but I know for some teams it's a great thing to have as common ground. Not opposed to the idea, just not super driven to solve it right now, personally. Just some context :slightly_smiling_face:
"""

**Comment by marcelocra** [comment]
Hey there! Great work, folks!

Is this something we still want for the project?

**Comment by Olical** [comment]
Hey! Yep, I would argue that this could be reopened or a new issue created to call out to newer nREPL ops that format code nicely. I wouldn't want to shell out to cljfmt or clojure-lsp though, only nREPL+CIDER since I want to keep Conjure focussed on that.

Personally though, I'd still recommend people get LSP set up and rely on that, it's really good for this sort of thing. Conjure is for talking to your running programs, getting stuff like formatting is a non-essential nice to have since there's other ways to do it in my opinion. So it's optional if it's easy to do it well from Conjure, but I don't want Conjure to be a "all in one" Clojure tool, it's just one part of your toolset, static analysis with LSP is another one etc.

So, if we think nREPL has a great hook for this these days, a new issue to implement that op could be good.
