### ISSUE TITLE
External Fennel evaluation (non-Aniseed / Neovim based)

### ISSUE THREAD

**Issue by leiserfg** [Olical/conjure#115]
It will be nice to interact with a fennel hosted elsewhere (löve2d, awesomeWM, ...) so one can make interactive development with those.

**Comment by Olical** [comment]
This has been something I've wanted to do for a while! It's not supported yet because I'm not sure how best to do it... I guess you'll want to start a Lua process with a Fennel REPL on the side? I'd like to find a way to support things like Love, Awesome _and_ hammerspoon (OSX automation that someone else wanted).

I need to do some research into this, if anyone has any ideas about what kind of remote REPLs or STDIO REPLs are available for this sort of thing, I'd love to know! The best thing we could have would be a REPL running inside the target process exposing a port Conjure can talk to.

**Comment by Olical** [comment]
I've renamed the issue to reflect what needs to be added so that more people can hopefully add their ideas and thoughts on this. I hope that's okay!

**Comment by leiserfg** [comment]
Maybe you can delegate the remote part to https://gitlab.com/technomancy/jeejah so you only need to provide a way for using the nREPL client on fennel?

**Comment by Olical** [comment]
Ah hah, yes, this is like the 4th time I've stumbled across it! I do have an nREPL client implementation in the Clojure client that I'm going to refactor out to make it reusable soon. That'll be a great solution! I'll report back in here when I have progress to share :smile:

**Comment by Olical** [comment]
So I found some issues with jeejah and gave up on it, but I wrote a bunch of code for the Racket stdio support that will be great for Fennel. So we'll be able to copy the Racket support and modify it for Fennel I think!

**Comment by Olical** [comment]
Released in [v4.10.0](https://github.com/Olical/conjure/releases/tag/v4.10.0)!

I haven't managed to get a Fennel REPL working toooo well with LOVE just yet but this is very promising: https://gitlab.com/alexjgriffith/min-love2d-fennel
