### ISSUE TITLE
Eval error with io.write in Fennel

### ISSUE THREAD

**Issue by lc9er** [Olical/conjure#116]
I stumbled across an issue when evaluating a region of code with 'io.write' in Fennel. With the following code, the results get written across the screen, from the start of the cursor, rather than to the log. 

```Fennel
(fn build-list [mystring range ?sep]
  (for [i 1 range]
    (io.write mystring i (or ?sep "\n"))))
(build-list "user_0" 10)
```

I've attached a screenshot to help explain.  

Neovim 0.4.4
Conjure: 4.4.0 (using aniseed and fennel that shipped with it)
Win10 1909
WSL 1
Ubuntu 18.04
![conjure_io write_error](https://user-images.githubusercontent.com/20189855/93404314-dd7cac80-f857-11ea-902f-f81243e8d92d.GIF)

**Comment by Olical** [comment]
Hmm so I capture stdout from Aniseed+Fennel code with [with-out-str](https://github.com/Olical/aniseed/blob/e2eef631f580ff8582d70ea12f0cb02716b24825/fnl/aniseed/nvim/util.fnl#L33-L48) (which I invented for this and modelled it on how Clojure behaves).

It works for `print` and other nvim based echo things but I guess `io.write` bypasses _everything_ and actually ends up writing into the stdout of nvim itself? That's bypassing everything I have access to I think :thinking: I don't know if there's a way I can ever capture that data without overriding the `io.write` function (I really don't want to do that).

Rather than `io.write`, could you get away with using `aniseed.string`'s `join` function or something then using `print` or `aniseed.core`'s printing functions?

**Comment by lc9er** [comment]
It looks like I may have to expand on the original idea to get it working (possibly - still a lisp newbie), but I think I can make that work. Thanks for your help!
