### ISSUE TITLE
How to remap some commands?

### ISSUE THREAD

**Issue by tami5** [Olical/conjure#117]
Hi there, I'm trying to remap, or perhaps map some commands under g as a prefix. I know there is an option to remap stuff, but how to call a function so I can map it? for example eval inside form.

Thanks

**Comment by Olical** [comment]
Hey, so the only way to remap is by setting options before Conjure loads, this is because unmapping then remapping things after they're set is pretty tricky and stateful. It's very easy to get things in a weird state if you start trying to move mappings rather than reconfigure them before they're set.

See `:h conjure-mappings` for more information on remapping the global Conjure prefix to whatever you want or individual mappings. For instance, if you want "eval my current form" to be under `gce` (without the global localleader prefix) you can use `let g:conjure#mapping#eval_current_form = ["gce"]`. Wrapping the mapping in an array / list is a sort of DSL to opt out of `g:conjure#mapping#prefix` for that specific mapping. If you want to change the prefix for all Conjure mappings you can set `g:conjure#mapping#prefix`.

You can set the options to `v:false` to disable them completely, then you could set up your own mappings that called the Lua functions if you wanted. Such as `:lua require("conjure.eval")["current-form"]()`.

I hope this helps!

**Comment by tami5** [comment]
Thanks a lot!

**Comment by zakrywilson** [comment]
Is it possible to disable just the session key mappings, e.g., the `<localleader>s` commands? They are interfering with my existing keybindings
