### ISSUE TITLE
Open log buffer by default?

### ISSUE THREAD

**Issue by bollu** [Olical/conjure#119]
Hello,

Thanks a lot for the amazing plugin! 
I was hoping it was possible to have the log buffer open by default. I currently need to use the key-bind:

```
<localleader>lv
```

when I open a new clojure file to get logging. I was hoping to setup `conjure` such that, by default, I have a vertical split when I open a new clojure file.

**Comment by Olical** [comment]
Hmm this is a pretty niche behaviour, I can't see many people wanting a log buffer constantly on display but I could be wrong. I'd highly recommend a custom autocmd for this.

 * On `autocmd filetype clojure` run a function.
 * Check if `g:clojure_file_type_loaded` is set (your own variable), if it is, do nothing.
 * If it wasn't set, send the keys to open the log and set `g:clojure_file_type_loaded` to true.

That way it opens on your first Clojure file but then stops. That could get as clever as you wanted and could even be it's own plugin, I'm not sure about adding it as a core feature though since there's a LOT of open questions about how it would work.

In my experience, anything that has nuance and isn't very clearly defined ends up making some happy and some unhappy, then I end up adding more and more configuration for that thing :grimacing: the best bet is usually "add a bit of viml/lua/fennel that does exactly what you want".

I promise it's best in the long run :smile:

**Comment by bollu** [comment]
Great, thanks for the solution!

I'm wondering if my workflow is somehow "wrong": I find it useful to have the log buffer open because the log messages to get "cut off" if they're too long? I thought the default solution is to have the log buffer open at all times.
Maybe I'm doing something wrong! Is there a better solution?


![ss](https://user-images.githubusercontent.com/1694861/95287966-ea078a00-0884-11eb-8c47-1b12215e5e73.png)

**Comment by Olical** [comment]
Hmm, so it _should_ scroll off the bottom if the result is too long, so for an individual eval, if it results in 100 lines, you'll only see the top ~30 in the HUD since they're probably the most interesting.

On the next eval you'll see the first lines of that result and it'll push the previous result out. If you're _not_ seeing this and things are just scrolling off screen then you've hit a bug! Would you be able to capture a https://asciinema.org/ or something of this so I can understand what's happening and when? Maybe you have a setting enabled that causes my auto scrolling to fail somehow? (or a conflicting plugin)

**Comment by Olical** [comment]
I pop the log open when I need to inspect a result closely or edit/yank/re-eval parts of it. Or to look at previous results of course.

I generally just rely on the HUD for 90% of my eval results though.

**Comment by Olical** [comment]
I'm going to close this for now because I feel like it's more of a workflow style thing than a technical issue with Conjure. Feel free to open if you disagree! We can also chat about this in the Discord or something if that's better :slightly_smiling_face:
