### ISSUE TITLE
[Feature Request]: Auto create a server if non, and connect to it .

### ISSUE THREAD

**Issue by tami5** [Olical/conjure#126]
Hey @Olical ,

It would be great if there is a way to auto create a server if non exists and connect to it. Currently I have extra dep for just that

```viml 
au BufEnter *.janet nn <silent><buffer><leader>es :silent! Dispatch janet -e \"(import spork/netrepl) (netrepl/server)\"<cr><c-j><c-w><c-q> 
```

It would be extremely useful if clonjure had a hook to accomplish this. I loved how with fennel we don't have to worry about this.

Thanks

**Comment by Olical** [comment]
The only reason this isn't a concern in Fennel is because we're running within the Neovim instance itself. I haven't really set a precedent for this, I recommend [vim-jack-in](https://github.com/clojure-vim/vim-jack-in) for Clojure for example, I would prefer this to be a seperate dependency or your own mapping / command.

It just adds a lot more maintenance overhead for me in terms of documentation, configuration and code to make it work properly when it's a feature that is extremely well suited for a 3rd party plugin or custom snippet.

I think the cost of my maintenance time to benefit just isn't quite worth it, this sort of thing works great as a standalone plugin (just like vim-jack-in) where it's tooling agnostic and can have it's own config / docs / issues / PRs.

Conjure is all about sending the right code to the right place and displaying the results in a way that allows you to explore and recall information easily. I definitely want to try my best to keep those boundaries fairly clean to ensure I don't overstretch myself and the codebase into maintenance hell.

**Comment by tami5** [comment]
> It just adds a lot more maintenance overhead for me in terms of documentation, configuration and code to make it work properly when it's a feature that is extremely well suited for a 3rd party plugin or custom snippet.

I Totally agree, just coming from vim-iced I was by spoiled IcedInstantConnect :D. I'll try and create custom command that would simple check if a janet server is running and spawn one other wise

Thanks
