### ISSUE TITLE
Initial Scheme stdio support

### ISSUE THREAD

**Issue by Olical** [Olical/conjure#129]
Should support multiple Scheme implementations over stdio, very much like Racket (but without xrepl I guess).

**Comment by taw10** [comment]
Hi, great work with Conjure!  I'm interested in a Guile client, and may even be able to develop and maintain it (pending getting up to speed with Fennel).

Guile offers a socket-based way of connecting to a running process (run "guile --listen=").  It's just a REPL running over a socket, the same as over stdio - no nREPL or similar - but I think it would be the best way to make a client.  Almost all of the code could be shared with a stdio client, just with the I/O going to a different place.  The socket can be a TCP socket or a Unix domain socket - the latter is preferred for security (see CVE-2016-8606 - Guile has a mitigation for this, but it's still better to avoid a network socket if possible, even on loopback).  Starting Guile using option "-q" (skip loading user init file) will avoid a repeat of issue #166.  

Some thoughts:  I think that having one client for all Scheme implementations might not be a good idea.  Sure, they share the same basic language, but that's where the similarities end.  Different implementations will need interfacing in completely different ways - different REPL commands to change module, different module systems, or even different ways of connecting (e.g. the REPL socket is not general to other Scheme implementations).  It seems to me that the clients are about the specifics of how to interact with the language implementation, rather than being about the language itself.  Or, did I misunderstand?

Finally, is there a reasonable way to make the configuration work with "dotted filetypes"?  See for example this [Guile mode for Vim](https://gitlab.com/HiPhish/guile.vim), which sets the filetype as "scheme.guile" so as to only make minor changes to the basic Scheme mode.  Setting the default in fnl/conjure/config.fnl works fine, but choosing the client in init.vim causes some trouble:
```
let g:conjure#filetype#scheme.guile = "conjure.client.guile.socket"
----> E121: Undefined variable: g:conjure#filetype#scheme
```
I've put my initial hacking on a Guile stdio client here: https://github.com/taw10/conjure (not ready for a PR yet - still needs to become "module-aware").

**Comment by Olical** [comment]
So very quick reply, just to ack, this is really cool! And the socket sounds good to me, there's some reusable "transport" modules already, so it'd be a new one of those presumably.

Having a client for each Scheme probably makes sense if they vary enough, yeah, then it's just a case of switching them out at config time depending on what you want.

Clients are basically drop in replacements that handle specific actions from the generic Conjure outer shell of UX. So they expose hooks like "eval this given string", they are engineered to match up to a specific filetype (which is awkward for Scheme since they're all Scheme!). So Conjure shares the same core UX and mappings completely generally but routes function calls to the right client depending on the filetype of the buffer you're in.

Oh! Dotted filetype! Yeah that should work, your issue there is that the vim syntax thinks you're trying to set the `guile` key of a map called `g:conjure#filetype#scheme`. You'll probably want something like `:call set(g:, "conjure#filetype#scheme.guile", "conjure.client.guile.socket")` (may be incorrect viml). That also might not work, but I'm sure there's a way to do it! You'll want to set this in `fnl/conjure/config.fnl` to make this a default.

I might need to hack around to support it, but I think we can get it working with the existing code tbh. If you have a crack at this and get it working to some point I can always refactor it into reusable Fennel modules etc if that's feeling too foggy to you but it's working :slightly_smiling_face: but I can also code review and leave that down to you if you wanna.

**Comment by Olical** [comment]
Thank you so much for showing interest and taking the initiative! It's so cool to see! :tada:

**Comment by taw10** [comment]
See #178 for some code!  I've also split off the discussion about dotted filetypes to a separate issue #177.

**Comment by Olical** [comment]
Just FYI I'm still deep in the process of modifying the guile client. Will share my changes soon! Basically just around UX and lifecycle to make it a little easier to debug and understand as a new user. It explains connection failures a little and I want it to handle the REPL hanging up, for example.

Once I'm happy with all the cases and behaviour I'll get this into a tagged release :)

**Comment by taw10** [comment]
Sure, the UX I came up with should definitely not be taken as the final word.  Sounds great, looking forward to testing the revision!

**Comment by Olical** [comment]
Okay, changes pushed! See the recent commits on the develop branch, mostly this one https://github.com/Olical/conjure/commit/084cbce8e7db3f6fbddf686e37c7da78b5f7c25e

**Comment by Olical** [comment]
And a first pass at the wiki entry https://github.com/Olical/conjure/wiki/Quick-start:-Guile-(socket)

**Comment by Olical** [comment]
I think you made the first ever wiki edit @taw10 :D thank you!

**Comment by taw10** [comment]
Looks great, and much tidier than my version!  I found one small(ish) problem, which I think was there before and might apply to other stdio-style clients as well - I'll put in a separate issue.
