### ISSUE TITLE
Does completion items has doc, function params?

### ISSUE THREAD

**Issue by tami5** [Olical/conjure#151]
Hey @Olical, does completion items has doc, function param?

I'd like to extend https://github.com/tami5/compe-conjure to include documentation popup.

Thanks

**Comment by Olical** [comment]
It does for Clojure since that's the only language that I can get that information for right now. I already have it popping up for `Plug 'Shougo/deoplete.nvim' | Plug 'ncm2/float-preview.nvim'`

![Screenshot_2020-12-23_12-32-27](https://user-images.githubusercontent.com/315229/102996382-f5c92b00-451a-11eb-9f3d-3128c0e8c9f5.png)

**Comment by tami5** [comment]
Nice, Thank you 🙏
