### ISSUE TITLE
Integrate clojuredocs for clojure client

### ISSUE THREAD

**Issue by tami5** [Olical/conjure#152]
A function and mapping that gets docs for a keyword from https://clojuredocs.org. This is awesome feature was first experienced with vim-iced.

Usage:

- Under a keyword, e.g. `use`, 
- hitting `<leader>hh` or something similar. 
- Fetch and parse https://clojuredocs.org/clojure.core/use to markdown with definition, usages, see also  and notes
- Open a center popup or new split with markdown ft containing the content

**Comment by tami5** [comment]
Hitting enter or c-] on see also item should re-run the function and replace the buffer content with it

**Comment by Olical** [comment]
Ah a neat idea, although I wonder if this should be a completely standalone plugin :thinking: maybe something that can hook into Conjure's tooling, functions and REPL connection, but it feels like it could be quite complex to build and maintain. I want to avoid adding whole huge sub-systems that I'll struggle to maintain to a high degree of quality.

This could be a really cool sister project to Conjure, I would like to see the more ambitious additions and features being optional 3rd party plugins that hook into Conjure's internals. What do you think?

Because i think this would be pretty difficult and time consuming to do myself right now, I'm trying to focus on smaller things that benefit every language supported by Conjure where possible.

**Comment by tami5** [comment]
You are right this might be better as a separate plugin. But again as I've seen with my work on telescope.nvim this might be a hassle for clojure developer who would like to just plug and play.

I'm going to open a pr for that. I thinking of simply creating a single file named usage-popup.fnl . 

I'm considering integrating janet docs as well. Although it may not be used as much as clojure since that site contains few examples.

What you think? btw I'm totally fine with a separate plugin.

**Comment by Olical** [comment]
Done by @tami5 over in https://github.com/tami5/lispdocs.nvim 😄

**Comment by idanko** [comment]
@Olical @tami5 it looks like cider already hase built-in table of clojuredoc, and exposes it via `clojuredocs-lookup` api call.
