### ISSUE TITLE
latest conjure can't find conjure.aniseed.macros

### ISSUE THREAD

**Issue by BerkeleyTrue** [Olical/conjure#159]
Updated to the latest conjure and started having this issue while evaling fennel code.

If I set conjure client fennel to use my installed aniseed version it seems to work fine

![image](https://user-images.githubusercontent.com/6775919/103433724-51468900-4bab-11eb-804b-b9ecd8fbc746.png)

conjure pointing to main
aniseed to develop
Both updated to latest

Neovim ver
![image](https://user-images.githubusercontent.com/6775919/103433735-8521ae80-4bab-11eb-8fe5-78dbee34a873.png)

**Comment by Olical** [comment]
Hmm I saw someone else mention this the other day too, sorry about the issue! Nothing changed around here as far as I know, I have a small hunch now though that it's to do with my embedding of Aniseed not copying all the right files 🤔 will dig into this tomorrow morning! Had a lot of family time recently so not much time for side project work over the past few days 😅 back to day job work on Monday!

I hope you had a great New Year!

**Comment by Olical** [comment]
Also, which plugin manager are you using? Packer? I'm struggling to work out why some people see this and others don't, I'm worried it's because the runtimepath isn't populated in the same way for every user.

**Comment by Olical** [comment]
Ah, packer, I went and found it :smile:

**Comment by Olical** [comment]
Hmm I've tried adding Conjure to the runtimepath on develop, because I rely on runtimepath still but packer doesn't update it, so this way I hope it'll support rtp _and_ packer. Might make no difference but worth a shot!

**Comment by Olical** [comment]
I still can't think of a way around this other than you manually adding the Conjure directory to your `runtimepath` manually until this issue on packer is addressed: https://github.com/wbthomason/packer.nvim/issues/71

Basically I don't have access to a `runtimepath` _or_ a `package.path` (I think, although not sure about that one) that contains all the plugin directories with packer like I do with every other plugin manager.

The Fennel compiler does not have the same resolver support as the underlying Lua, as in, Fennel requires me to set a string of paths for it to search for macro files. This is why this error happens, the Fennel path is empty and it can't find the macros because I seed the Fennel path with the `runtimepath`.

What I try to do is take every plugin you have installed and add their `fnl` directories to your `fennel.path`, I just can't do this with packer, the information does not exist as far as I'm aware. If someone can tell me how to get a list of paths to all installed plugins with packer I can try to implement a solution, but I don't think I can work that out myself.

**Comment by Olical** [comment]
Although saying that... if you could confirm that your `package.path` contains Conjure @BerkeleyTrue, maybe I _can_ rely on that instead of the `runtimepath`!

**Comment by Olical** [comment]
How's `develop` for you now, @BerkeleyTrue? I'm basing `fennel.path` off of `package.path`, which may be set up correctly by packer but I have no idea, I'd have to swap too much to try it out for today, starting work very soon :sweat_smile:

**Comment by BerkeleyTrue** [comment]
@Olical Just tried the latest and I tried 6b660d0. Neither seemed to have any effect. Maybe this is just the life us `packer` choose. I can dedicate some time to investigate this weekend to debug. I tried adding conjure to the runtime directly myself. 

Also, just to add info, I'm using a symbolic link in my pack directory. Not sure if that has any effect.

**Comment by BerkeleyTrue** [comment]
Actually the latest aniseed develop breaks compiling completely. 

![image](https://user-images.githubusercontent.com/6775919/103798376-73eafe80-4ffe-11eb-8509-5031c1b03e3e.png)

Going back one commit (to before 8e4372a) and it works as usual.

**Comment by Olical** [comment]
Hmm, all I did was base `fennel.path` on `lua.path`, I wonder what could be causing this, I guess it's another packer oddity? I don't think I can support packer until they support runtimepath like all the others. I can swap the code back to how it was (basing `fennel.path` off of runtimepath), but it still won't support packer until they change.

**Comment by BerkeleyTrue** [comment]
I've printed out the results of path of lua, aniseed fennel pre 8e4372a,and conjure aniseed fennel path. 
Only my aniseed fennel path has conjure lua/fennel dirs available. It looks like conjure.aniseed.fennel.path is just seeing a duplicated lua path which is also does have access to all the files. 


![image](https://user-images.githubusercontent.com/6775919/103961566-987fcd00-5109-11eb-87b0-06f3eeefa643.png)

**Comment by BerkeleyTrue** [comment]
echoing the runtimepath and package.path right before conjure.aniseed.fennel path is set. The runtimepath has conjure but the lua path does not. Reading the docs, it looks like anytime runtimepath is updated package.path is supposed to be updated. So maybe this is an issue with neovim?

**Comment by Olical** [comment]
So packer _is_ putting Conjure in the runtimepath? :eyes: I can work with that.

**Comment by BerkeleyTrue** [comment]
Well, I think it's vim packages that is adding them to the run time them, then loading the plugins. Unlike vim-plug, removing a plugin from the packer conf does not disable it if it is in the start directory. It still gets loaded.

**Comment by Olical** [comment]
So, I've swapped back to sourcing the `fennel.path` from the `runtimepath`, which may work for you? I've also added a few functions you can use.

## When you update your `runtimepath` after Conjure has loaded

```lua
-- Resync the runtimepath into fennel.path at a later time.
require("conjure.aniseed.fennel")["sync-rtp"]()
```

## When you want to add a specific directory to your fennel.path

```lua
-- A manual override if nothing else works, add the paths to the fennel you're interested in.
require("conjure.aniseed.fennel")["add-path"]("/home/ollie/.local/share/nvim/plugged/conjure/fnl/?.fnl")
require("conjure.aniseed.fennel")["add-path"]("/home/ollie/.local/share/nvim/plugged/aniseed/fnl/?.fnl")
```

So I kinda don't have high hopes for the runtimepath sourcing over package.path, but the manual adding / delayed call to `sync-rtp` miiiight solve you issues? I know it's not ideal but there's honestly no way to do this until packer has a path string like every other vim package management solution, while it avoids paths I can't build a path for fennel (which only supports path strings).

**Comment by BerkeleyTrue** [comment]
Ok, I finally know 100% what the issue is. It's not an issue with vim packages or packer but it's a race condition.

According to the docs, vim first sources the init file, then adds all the packages to the runtime.

At the end of my init file I call aniseed.env.init, which loads all my fennel code.

In that code, I require conjure to add it to my custom completion sources.

This loads the conjure module into memory, which runs the sync-rtp as a side effect.

Since my init file has not completed running, vim hasn't processes the packages to add them to the rtp and so fennel.path is not properly hydrated.

I debugged by adding print statements to the sync-rtp call, before my aniseed.env.init call and at the very end of my init.lua file. I can see that sync-rtp is called before the end of the init file. If I comment out the require of conjure in my files, the first sync-rtp call does not happen until after init lua ends and by that point the rtp if fully hydrated.

Also, A package can be loaded using lua requires but that this does not effect the runtimepath. Or at least it does not add it to the path until after the package is loaded into memory, so after sync-rtp side effect. 

Easy solution is to call `packadd conjure` before the aniseed.env.call if a user is going to require conjure within their fennel code.

Another possibility is to have aniseed.env.init call somehow happen after init is source, as in defer until nvim is free, but this would probably have a lot of unintended effects.

Another possibility is to have conjure check if it exists in the runtime on the first interaction with the user and if not, re run sync-rtp. 

I think I'm satisfied as is and will just call packadd before aniseed.env.init.

Let me know if you want me to close this.

**Comment by Olical** [comment]
I think I'll close this for now because I'm just glad you have it working, I think maybe adding a FAQ entry about this would be good though, I can do that if you can provide me with a succinct solution and your specific setup? Or feel free to add it yourself, I'm sure many people will find it very helpful. https://github.com/Olical/conjure/wiki/Frequently-asked-questions

I'll probably link to this entry from the README too, just under the install step with a caveat. So is it a race condition when you're using packer? Or some other combination? Because I always through packer was the common theme with this issue :thinking:

Thank you for digging into the problem! I'm sure it was very frustrating, so thanks for chasing it down and not giving up! :tada: 

You can always call sync-rtp again now, after things are loaded, if that's easier. Although it probably doesn't help, re-syncing is an option now that I've exposed it as a function.

**Comment by wbthomason** [comment]
Just as a note (in case you add a warning to the README/in case anyone sees this issue): I would expect that this will be a problem with **any** plugin manager based on native packages (e.g. also `vim-packager`, `paq.nvim`, `minpac`, etc.). The usual fix (e.g. as documented in https://github.com/wbthomason/packer.nvim/issues/4) is to either (1) manually `packadd` before you need a function from the relevant plugin (as @BerkeleyTrue discovered) or (2) to keep plugin-relevant code out of `init.vim` and instead put it somewhere under `plugin/` or some other location that gets sourced after packages. This latter approach is slightly complicated by the new `init.lua` feature, as there's no equivalent to `plugins/` (in the sense of being automatically loaded at some predetermined point in the startup sequence) for Lua code.

Hope this helps!

**Comment by cideM** [comment]
I think my problem might be related to this but I'll add some point create a separate issue. If I lazy load Conjure by doing a `packadd conjure` in my Clojure `ftplugin` then I only get the basic Conjure `:` commands. I can call `:ConjureConnect` and it opens a little hover window indicating a successful connection, but after that I don't get the Conjure mappings and full ex commands.

**Comment by Olical** [comment]
Are all of these related to using `aniseed.env` or am I missing something here :thinking: if I made it so using `aniseed.env` (Aniseed/Fennel dotfiles) was through setting an option like `let g:aniseed#env = v:true` instead of a function call, would all of these problems go away?

That way you never call into Aniseed or Conjure, you only set global options that it picks up when loaded. I feel like that's a much better approach! Any thoughts?

**Comment by gpanders** [comment]
> This latter approach is slightly complicated by the new init.lua feature, as there's no equivalent to plugins/ (in the sense of being automatically loaded at some predetermined point in the startup sequence) for Lua code.

Just to clarify for any future visitors to this thread: `*.lua` files under the `plugins/` directory are now automatically sourced on startup as of Nvim 0.5.0, so this is a perfectly valid approach now.

**Comment by Olical** [comment]
@gpanders oh interesting! Do you know where this is documented / explained?

**Comment by gpanders** [comment]
> @gpanders oh interesting! Do you know where this is documented / explained?

https://neovim.io/doc/user/starting.html#load-plugins
