### ISSUE TITLE
Support tpope/vim-repeat plugin

### ISSUE THREAD

**Issue by dharrigan** [Olical/conjure#171]
The [https://github.com/tpope/vim-repeat](vim-repeat) plugin allows commands to repeated easily.  As a plugin author, it would be great if Conjure supported repeating commands, so far I have these:

```
silent! call repeat#set(",ee", v:count)
silent! call repeat#set(",ece", v:count)
silent! call repeat#set(",er", v:count)
silent! call repeat#set(",ecr", v:count)
silent! call repeat#set(",ew", v:count)
silent! call repeat#set(",ewc", v:count)
silent! call repeat#set(",eb", v:count)
silent! call repeat#set(",gd", v:count)
silent! call repeat#set(",tn", v:count)
silent! call repeat#set(",tc", v:count)

```

But you can add as many as Conjure supports. Perhaps them all?? Or just the ones that make sense?

Here are some examples of how other plugin authors "plug into" the vim-repeat plugin

`https://github.com/glts/vim-radical/blob/master/autoload/radical.vim#L198`
`https://github.com/tpope/vim-surround/blob/master/plugin/surround.vim#L477`
`https://github.com/tpope/vim-unimpaired/blob/master/plugin/unimpaired.vim#L188`

Thank you kindly.

**Comment by dharrigan** [comment]
Not sure works like I've done it.

Adding the call's into my vimrc, doesn't make it work.

I *think* the Conjure plugin has to do it, with a `\<Plug>` type of format?

**Comment by Olical** [comment]
I don't _think_ `<Plug>` is required, since that's really just a mechanism for providing mappings you can't physically press until you map them yourself (something I don't adhere to since I have a chunk of defaults with a config system to change them).

It's almost definitely just because I need to call that repeat function just after the mapping fires... I think? And the `v:count` will be the count provided to the mapping at "press" time :thinking:

**Comment by Olical** [comment]
Think I know how it works :smile:

**Comment by Olical** [comment]
Should be working on develop now :smile: let me know what you think!

**Comment by dharrigan** [comment]
Seems to work fantastically well!

Thank you very much!!
