### ISSUE TITLE
Julia and tree-sitter support

### ISSUE THREAD

**Issue by savq** [Olical/conjure#184]
Hi, I found about Conjure a while ago, and while I can't say I've used it a lot, I find the premise great. This is by far the best REPL-plugin I've seen for Neovim.

I saw in the repo that non-lisp languages would be supported once Neovim has tree-sitter support, which is great! I've also been meaning to do some stuff with tree-sitter.

With all of that said, I'd be very interested in adding Julia support to Conjure.

I've already done a very rough draft [here](https://github.com/savq/conjure-julia). So far it only prints the text representation of the nodes to the nvim prompt, but these would be the same strings that Conjure would have to send to the REPL.

Since the folks over at [nvim-treesitter](link) have already done most of the hard work, I've just used some of the helper functions provided there. This also means that it'd have to remain a separate repo, so as to not add a dependency (and 0.5 requirements) here.

I wanted to know some opinions on this before moving forward. I know Conjure is waiting for 0.5 to stabilize, but I have time to spare these days, and I'd like to get something working in the mean time, at least for myself.

**Comment by Olical** [comment]
Oh this is a wonderful example! I've been meaning to begin experimenting but I just don't have the time / brain space (especially recently), so your research here really lowers the barrier to entry. Thank you!

I could translate your examples into Fennel and integrate them into the `conjure.extract` module under a feature flag for people to opt into. Eventually that feature flag will be the default, then, some day, I'll delete the paren hunting code that's currently there.

Once that feature is in you'd be able to write a regular Conjure client for any language with the caveat that it asserts and throws an error if the tree sitter mode isn't enabled (or maybe your client module just exposes a `tree-sitter? true` value, probably that).

**Comment by Olical** [comment]
`conjure.tree-sitter` is now a thing :smile: it's not hooked up to anything yet, but I've translated it to Fennel and added a link to your original repo. I hope that's okay? I've been putting thought into how we determine if we have the following requirements to use it:

 * Neovim 0.5 with tree-sitter
 * https://github.com/nvim-treesitter/nvim-treesitter (will this be part of the core nvim some day?)
 * The appropriate `:TSInstall [filetype]` already set up. Maybe I could call this for the user but that feels... presumptuous. Also it requires a bunch of things to work, so I'd rather not have Conjure checking if you have a working `gcc` copy :stuck_out_tongue:

I'm also musing on how each client can reject or accept nodes when looking for forms. So when you hit `<prefix>ee` to evaluate the current form under the cursor it'll ask the client "is this evaluate-able?" as it walks up the tree, rejecting results until it hits something with children that the client thinks it can eval.

This means lisps can say "no, it needs to start with an opening parenthesis" and non-lisps can inspect the node further to say "is this a node of type x, y or z?" because they might not be able to eval `(my, arguments)` but can eval the parent, `function (my, arguments) { ... }`, for example.

I think only one "is this a valid form" question is required for each client to support tree-sitter :thinking:

**Comment by Olical** [comment]
Until I hook this up, you could always hack your client to ignore the code Conjure provides (probably nil or an empty string for julia) and instead call out to this module directly.

**Comment by Olical** [comment]
Found my first tree-sitter bug already :grimacing: 

```
;; This is okay
(+ 1
   ;
   )

;; This is not
(+ 1
   ;
   2)
```

It ends up parsing out `(+ 1` and then just stopping, missing the rest of the form. I guess it's an issue with the fennel grammer?

**Comment by Olical** [comment]
If you want to try this out, set `g:conjure#extract#tree_sitter#enabled = v:true` (see `:h conjure`) and ensure the conditions mentioned in my previous comment are met (up to date, plugin installed, filetype support compiled).

Then the code passed to your client will come from the tree sitter forms! I haven't used it for extracting the word under the cursor since I don't really see a need for that right now, the current implementation seems to work well, I found a bunch of caveats and complexities with getting the current "word" with tree sitter. I like vim's existing definition of `(nvim.fn.expand "<cword>")` enough already.

**Comment by savq** [comment]
> conjure.tree-sitter is now a thing… I've translated it to Fennel

That's all great! I don't have a problem with moving the thing to Fennel. I'm more familiar with Scheme but (tomato (tomato)).

> I'm also musing on how each client can reject or accept nodes when looking for forms.

Yep, that's the main design problem. In Julia's case it's not that bad. Almost everything will evaluate to something, but even when things are valid, some evaluations will be very trivial.

> they might not be able to eval (my, arguments) but can eval the parent, function (my, arguments) { ... }, for example.

That's a good example. In Julia, a parameter list _is_ a tuple, and it'll be evaluated as such. But who cares about the tuple? The sensible thing to do is evaluate the function (and have a less used command that can eval the tuple, just in case).


> I haven't used it for extracting the word under the cursor since I don't really see a need for that right now

Yeah, the "word" thing is phrased wrong. _Atom_ would be a more appropiate name, since it can also evaluate strings and other literals. I wrote that as a  first test, but it might not be necessary.

**Comment by savq** [comment]
With all that said, I've had trouble with neovim/neovim#14044, so I'm not in a rush to add more features to the prototype.

In the mean time, I'll look into setting-up aniseed and skim the Conjure code base.

**Comment by Olical** [comment]
FYI you won't need Aniseed to work on Conjure... or you shouldn't do? Aniseed is purely for writing your nvim conf or plugins in Fennel+helper macros. Conjure ships with it's own Aniseed and anyone should be able to run `make` to rebuild everything in Conjure.

If you have Conjure installed (I point my plugin manager at the local git copy to work on it) then you can automatically work on Conjure using itself :smile:

**Comment by theHamsta** [comment]
> (will this be part of the core nvim some day?)

all the Tree sitter functions you used in `tree-sitter.fnl` are already in upstream nvim with the exception that `get_node_text` does not support multiline text yet. I have a PR to fix this prepared. Just need to do some more tests.

**Comment by savq** [comment]
Thanks @theHamsta, that's good to know. I was mostly following the docs.

> About getting the root node get_parser():root() is also fine.

Yeah, nomenclature is not my thing 😞 The root function is used to get the root of a form (the Conjure root, not the tree-sitter root). It'll probably need to handle special cases so it doesn't evaluate whole modules or classes.

**Comment by theHamsta** [comment]
You probably want some similar logic as in https://github.com/nvim-treesitter/nvim-treesitter-textobjects . `find_best_match` let's you filter queries based on a criterion (e.g. cursor in node range) https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/b0f6d2c91b46faecee8b44f426de4b40d8ec8494/lua/nvim-treesitter/textobjects/shared.lua#L112

nvim-treesitter once even had paredit-like movements and edits. It's time that I dig out this code. It worked better for Lisps but was also ok for other languages.

**Comment by Olical** [comment]
Not sure if I 100% follow that line of thought, but I tweaked the root function to basically recursively walk up parents until it finds a node that is one step down from the "root" document level. I.e. a form at the top level of the file, but not the entire file. Works well! I should look into queries and things eventually but walking the tree recursively is already infinitely better than the paren character hunting I was doing before!

**Comment by Olical** [comment]
Mayyyybe resolved by the recent PR merge?

**Comment by Olical** [comment]
@TerseTears did this! It works with tree sitter! Wow! 🎉
