### ISSUE TITLE
Namespace Metadata Breaks Evaluation

### ISSUE THREAD

**Issue by semperos** [Olical/conjure#204]
Howdy 👋 

clj-style will transform metadata like this:

```clj
(ns ^{:clj-kondo/config {:lint-as '{my-awesome/defn-like-macro clojure.core/defn}}} foo)
```

Into metadata like this:

```clj
(ns ^{:clj-kondo/config {:lint-as (quote {my-awesome/defn-like-macro clojure.core/defn})}} foo)
```

The `'` version works fine with Conjure. The `quote` version does not and gives the following error if you invoke, for example, `ConjureEvalRootForm`:

```
; eval (root-form): (ns ^{:clj-kondo/config {:lint-as (quote {my-awesome/d...
; Namespace not found: ^{:clj-kondo/config
```

Thanks in advance for any time you have to help!

**Comment by Olical** [comment]
Thank you for raising this! I'm investigating now, I suspect it's to do with Lua's string pattern matching system not working quite how I thought it was. Luckily this area is easy to unit test, adding your examples there now 😄

**Comment by Olical** [comment]
Okay, should be fixed on develop! Let me know if that's done the trick for you! Thank you for catching it, I just had to swap some lines around, stripping the metadata part of the ns before I try to extract other information.

**Comment by semperos** [comment]
@Olical Thanks a million! 🎉  Works as expected.

**Comment by NoahTheDuke** [comment]
I believe this is broken when the metadata is across multiple lines. Below is the minimal number of lines I could get it to fail:

```clojure
(ns 
  ^{:doc "A BDD testing framework.
         
         
         
         
         
         asdf
         
         
         asdf
         asdf
         asdfasdf
         as
         dfasdf
         asdfasdfasdf
         asd
         as
         dfasdfasdf
         asdfasdfasdf
         asdf
         asdf
         "
   }
  lazytest.core
  (:refer-clojure :exclude [test])
  (:require
   [clojure.test]
   [lazytest.context :as ctx]
   [lazytest.malli]
   [lazytest.suite :as suite]
   [lazytest.test-case :as test-case])
  (:import
   (lazytest ExpectationFailed)))
```

Version: conjure commit 6d2bc7f
neovim: 0.10.0

**Comment by Olical** [comment]
This is due to this limit which we could raise significantly really, maybe even just the whole file.

https://github.com/Olical/conjure/blob/6d2bc7f7b24c2c43d54f263bee7b9b08aef5d1a1/doc/conjure.txt#L765-L774

I think I added it because it's checked on every evaluation and I didn't want to add too much pre-work to each evaluation, just in case HUGE buffers slowed down some machines.

The worst case scenario that a user would notice though would be as follows:

 - Slow machine
 - Large buffer
 - No namespace / module name so we search to the end trying to find it

That's actually quite unlikely... so maybe I'll default this value to `nil` and have `nil` mean infinite. So if a user is working in a project or language that would benefit from it then they can set it, but most users won't need it.

**Comment by Olical** [comment]
Changed the default on the `main` branch to `-1` which means "all lines". Also updated the documentation.

**Comment by NoahTheDuke** [comment]
Thank you. I should have checked the configuration before posting.
