### ISSUE TITLE
Racket evaluations return nothing after evaluating unclosed define

### ISSUE THREAD

**Issue by hi-im-buggy** [Olical/conjure#213]
## Summary
After evaluating a buffer with a `define` that hasn't been closed,
further evaluations of forms do not return values in the HUD or the log.

## Reproducable example

```racket
#lang racket

(define (foo a)
  (if a
	true
	false)
;; note the outer `define` has not been closed

(foo true)
(+ 1 1)
```

1. Move cursor to the `(+ 1 1)` form and evaluate it. Evaluates successfully and returns the correct value.
2. Evaluate the whole buffer. Returns nothing.
3. Move back to `(+ 1 1)` form and attempt to evaluate it. Returns nothing.

## System Information

- OS/Kernel: `Linux 5.12.6-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux`
- Racket: `v8.1 [cs]`
- Neovim: `NVIM v0.5.0-dev+1342-gde96626ad`
- Aniseed: `v3.18.0`
- Conjure: `v4.19.0`

**Comment by hi-im-buggy** [comment]
This can be band-aid fixed by restarting racket, and making sure not to evaluate any unclosed defines, but I think Conjure should raise an error in such a situation and be able to handle further evaluations on correct forms.

**Comment by Olical** [comment]
Thank you for the report, I'm investigating now. I can't think of a good way to fix it right now, I can't detect unbalanced parens really since that requires completely and accurately parsing the Racket source code. Ideally I'd be able to send some sort of control character to the REPL that will accept and flush the input, no matter the current state but I can't find a way to do that right now.

The `<c-c>` and `<c-d>` inputs in the stdio REPL kind of do what I want, I need to find a way to do that over a libuv process stream... 🤔 I think `<c-c>` is the best option for now, if I can find away to send an interrupt signal.

**Comment by Olical** [comment]
So I couldn't find a way to do this automatically for you without a mountain of caveats and potential bugs, so I did the next best thing.

I've added an interrupt mapping which should double as a fix for this issue as well as a useful tool for the future! it essentially sends a `<c-c> to the process for you which fixes hanging evaluations due to 100% CPU _or_ an unclosed paren. It's set to `<prefix>ei` by default, same as the one in Clojure.

I hope this helps1

**Comment by hi-im-buggy** [comment]
Thank you very much, `<prefix>ei`  works great! Seems like it'll be convenient for getting out of other sticky situations as well!

**Comment by Olical** [comment]
Sorry that I couldn't automate it completely, I may be able to detect this sort of thing _some_ day. But ideally I'd use something like nREPL for Racket eventually which will completely avoid any of these sorts of issues. I'm kind of shimming my own things on top of the stdio REPL which can get quite tricky. Simplicity is key, for now!
