### ISSUE TITLE
Lua error when opening .clj file

### ISSUE THREAD

**Issue by jakesunplugged** [Olical/conjure#227]
Hi there

Whenever I open a .clj file, I get the following error:

`Error executing vim.schedule lua callback: home/...../.config/nvim/plugged/conjure/lua/conjure/log.lua:344: Invalid key 'border'`

Thanks

**Comment by Olical** [comment]
Ah I think this is due to the new HUD border support which requires you to be on the latest version of Neovim (0.5+). This is the latest stable release and I think it's widely available? So an update may do the trick or you should be able to set `let g:conjure#log#hud#border = "none"` to turn off the HUD border.

It's because floating window borders are a new feature in 0.5+ and I guess the existence of the key throws an error pre 0.5 😞 this could be gated so border support doesn't cause errors in <0.5 but I'm not sure how long this will be an issue for as everyone slowly updates.

**Comment by Olical** [comment]
Oh no! Setting the border to none still provides the key, so your only option right now is to use the previous tag of Conjure (`v4.21.0`) or update Neovim. I think I need to make this key work a little differently to allow people that can't update just yet to use Conjure.

**Comment by Olical** [comment]
Fixed on `develop`, I'm now detecting if you have Neovim >= 0.5 and not setting the key if you don't.

**Comment by jakesunplugged** [comment]
Thank you. Updating Neovim fixed it!
