### ISSUE TITLE
Repeated `E730: using List as a String` errors on autocomplete/omnicomplete (shadow-cljs)

### ISSUE THREAD

**Issue by smolck** [Olical/conjure#239]
Title says it all. It's weird though, because it only seems to happen when completing functions starting with `in`, when around/on the `n` character? No idea why, or if it just seems that way, but here's a screenscast of the issue so you can see what I'm talking about:

https://user-images.githubusercontent.com/46855713/129630147-f1dec399-aa2b-4c02-8876-4aeff6df0a1a.mov

That video shows it happening with nvim-compe + compe-conjure autocomplete, but it happens even with the normal `<C-x><C-o>` omnicomplete. Also, whether `g:conjure#client#clojure#nrepl#completion#cljs#use_suitable` is true or false doesn't make this go away (at least from a quick test), if that helps at all.

EDIT: Also seems to happen when entering e.g. `(. js/document -style)` (although it seems inconsistent), so actually doesn't happen only on functions/things starting with `in`.

**Comment by Olical** [comment]
Hey thanks for reporting this. It's pretty weird that it's kind of inconsistent, and thank you for checking with that option on and off, that's helpful. I'll try to reproduce this soon!

**Comment by Olical** [comment]
Looking at this now, interestingly CLJS completion still doesn't work for me with `g:conjure#client#clojure#nrepl#completion#cljs#use_suitable` enabled, I remember this being broken a while back (upstream, not in Conjure) and I think it was fixed recently. So I might just need to update my local repro environment, just thought it was an interesting point.

I can also reproduce your issue if I try to complete `(i)`, just the `i` is enough, so it's not even `in`, I'm guessing some result from this `i` completion result has some weird data in it I'm not accounting for. Investigating with `let g:conjure#debug = v:true` now. Which I only mention because that little known setting can be really useful 😄

**Comment by Olical** [comment]
Found it! There's a `:doc` key coming back as an empty map instead of a string (like literally every other result) which translates into Lua land as an empty table which translates into VimScript land (where the completions results eventually end up) as an empty list! Since Lua tables are lists and maps and an empty one is indistinguishable from the other. I'll add some defensive code for this but wow, so weird that it returns an empty map there... guess it's nREPL encoding a null or something weirdly.

**Comment by Olical** [comment]
Fixed on `develop`! I also have some experimental Fennel / Aniseed work on the branch right now, so it should be stable for Clojure but you may see weirdness if you do any Fennel work until I stabilise and tidy it up.

**Comment by smolck** [comment]
Awesome, that works! Thank you for the quick fix!
