### ISSUE TITLE
Aniseed module does not properly source modules when evaluating a file or buffer

### ISSUE THREAD

**Issue by katawful** [Olical/conjure#240]
I am using Conjure to develop a plugin, and I'm having trouble with evaluation. When I evaluate a function in a main file, it will not import the changes I make to a different file. I have to evaluate that file, then go back and evaluate the main file. This holds true for any kind of evaluation. Both files are set up using Aniseed's module system, with the functions using the `defn` keyword. This massively slows development speed for me, and as far as I can not an intended feature

**Comment by Olical** [comment]
Hm, so you mean you have file A and B, where B depends on A, so something like

```fennel
(module A)

...

(module B {require {A A}})

...
```

And when you eval changes in the A file then go to use them from the B file, it's the old version?

**Comment by katawful** [comment]
The opposite. If I change A, then evaluate B, it will evaluate with the unchanged A. If I change A, evaluate A, then evaluate B, the changed A will evaluate

**Comment by Olical** [comment]
Oh, so you're changing `A.fnl` but not evaluating it then evaluating `B.fnl` and not seeing things get reloaded automatically according to dependency order. I'm afraid this is working as intended, autoload / require _will not_ reload code from source on each subsequent require, that's just how Lua works.

You need to remember to `<prefix>ef` etc after you change `A` in order for other modules to see those changes, if you change the file, write it to disk and then reload a different module those changes will not be applied since you only changed the source, not the loaded version.

A way you _could_ get around this would be to `(tset package.loaded :A nil)` before every load of `B`, this would mean Lua would reload the file from disk... which would actually be your old compiled Lua code so you would also need to run `make` and compile the fnl to lua.

I think the best approach here is to get into the habit of making changes to the source _and_ remembering to evaluate them into memory.

**Comment by katawful** [comment]
Ok, this is understandable. Certainly leaves me less confused. Going to close this because it's not a feature request, I can simply set up some autocommands to do what I want
