### ISSUE TITLE
Not integrated well with vim-racket ftdetect on #lang tags

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#339]
In racket we have [#lang shorthand](https://docs.racket-lang.org/guide/Module_Syntax.html#%28part._hash-lang%29) to specify current language.

For example:
```racket
#lang sicp

(inc 1)
```
Would be detected as DSL [sicp](https://docs.racket-lang.org/sicp-manual/index.html) in [vim-racket](https://github.com/wlangstroth/vim-racket.git), and filetype is set to sicp. However, this contradicts with conjure's backend detection via filetype. 

A trivial workaround will be:
```racket
#lang sicp
;; vim: set ft=racket: 

(inc 1)

```

But I think it would be better if conjure can somehow workaround this, e.g. by looking at the extension?

**Comment by Olical** [comment]
So under `:h g:conjure#filetypes` you'll find docs about hooking Conjure up to different buffers and filetypes. This config should do the trick:

```viml
let g:conjure#filetypes = ["clojure", "fennel", "janet", "racket", "scheme", "sicp"]
let g:conjure#filetype#sicp = "conjure.client.racket.stdio"
```

Which says Conjure should also load for `sicp` buffers and then those buffers should be handled by the Racket stdio client.

**Comment by Olical** [comment]
This can be added as a default if it's always what people want, but I'm not sure.

**Comment by glyh** [comment]
Yeah sure it works, but the problem is that racket has tons of DSLs.

**Comment by Olical** [comment]
There's no way I can support all of those DSLs ahead of time without Racket community config input 🤔 and I don't know how I can tell that something is a Racket file other than by extension / filename. So maybe I need to implement something special just for Racket since it's filetype varies in this way.

My suggestion for now is to add `:sicp :conjure.client.racket.stdio` to the config or include the inline vim config you mentioned.

Another thing that could be done would be for `vim-racket` to implement filetypes like some other filetype plugins where it sets the filetype to `racket.sicp` instead of just `sicp`... unless it's doing this already? Conjure has specific support for dot delimited filetypes so it'll pick up the `racket` part of it and know to use the Racket client.

**Comment by glyh** [comment]
Thank you. I'll try to talk to them.
