### ISSUE TITLE
Eval into register (eval-yank)

### ISSUE THREAD

**Issue by stelcodes** [Olical/conjure#349]
I'm not sure if this has been discussed before (I searched through the issues and couldn't find anything) but is there a way to eval-yank? I'm often making a comment with `<leader>ece`, yanking that, and pasting it somewhere. It would be rad to have a keybinding like `<leader>ey` that stuck the result of the evaluation into a register.

Conjure: v4.33.1
Neovim: v0.7.0

**Comment by sigvesn** [comment]
From the help text:

>   Every evaluation captures the result and places it in a Neovim
>   register for you to use however you want [...]

By default this is set to the `"c"` register. 

To change this and see the full text, use `help conjure#eval#result_register`

**Comment by Olical** [comment]
@sigvesn is right! That does exist in this sort of passive form, so you can evaluate something and then paste the register somewhere already.

This doesn't let you pick a register on the fly and I'm not completely opposed to adding that sort of mapping (although it'd probably take some rewriting of the mapping system to express it in code, data and docs). If you did _need_ on the fly register picking, it could probably be done through a custom user mapping that set the Conjure option just before the eval for now 🤔 

I set my `result_register` to `*` which works well for me, the default is supposed to be an uncommon but easy to remember pneumonic, although I do still feel kind of icky overwriting a user register passively. I admit I took the lazy way out with that one instead of implementing proper chorded mappings for it.

I do kind of prefer it though because I don't need to remember to yank _before_ I eval, I know I have it to hand if I decide I need to paste it somewhere after.

So, any thoughts? 😄

**Comment by stelcodes** [comment]
@sigvesn Oh my god I totally missed that! Thank you. @Olical I'm fine with `g:conjure#eval#result_register = "*"` so I'll just close this ticket and if anyone wants to work on adding a special `g:conjure#eval#result_register = "*"` mapping that could just be a new ticket.
