### ISSUE TITLE
All of a sudden Conjure giving LUA error

### ISSUE THREAD

**Issue by ketansrivastav** [Olical/conjure#360]
When i open a clj file or try to eval an expression:

![Screen Shot 2022-05-28 at 1 04 57 PM](https://user-images.githubusercontent.com/9023151/170815747-541d33b1-8e24-4236-a5d8-35f2aca311c4.png)

NeoVim:  version                                                                                                                                        
NVIM v0.7.0                                                                                                                                     
Build type: Release                                                                                                                             
LuaJIT 2.1.0-beta3                                                                                                                              
Compiled by brew@Monterey            

I have tried reinstalling Conjure and nvim

**Comment by Olical** [comment]
Hmm did you recently update Neovim? The last time I saw this was when someone had an out of date copy of Conjure. I've seen it twice actually, one where they had some config that kept their Conjure version pinned to an older one and another where they had a 2nd copy of Conjure on their path that was out of date and loading before the up to date version.

You NEED the latest version with Neovim 0.7+ because they are introducing breaking changes quite regularly at the moment. I'm keeping up with them but updating Neovim without having the appropriate fixes in Conjure will lead to issues.

If you're absolutely sure you're up to date I'll try to work it out but this is the EXACT error two people have had before you and both times they had an old version of Conjure loaded somehow 🤔

**Comment by ketansrivastav** [comment]
Thanks Olical, I  will double check the Conjure version. But I did remove the Conjure directory from plugins and installed again. I do remember that it stopped working after macOS update.

will let you know.

**Comment by ketansrivastav** [comment]
Shit, you were right, I was targeting a an older version of Conjure. Getting the latest fixed it.

Sorry, should have checked it before opening the ticket.

Thanks!

**Comment by Olical** [comment]
Eyyy I'm just glad it's fixed! This will happen to a lot of people as Neovim releases breaking changes and I add fixes for them. You're not the only one to run into the same issue and think it's a bug, it really looks like it. Don't worry! 😊
