### ISSUE TITLE
How do I make my formatter consistent with Clojure's styleguide?

### ISSUE THREAD

**Issue by Invertisment** [Olical/conjure#379]
The style guide https://guide.clojure.style/#code-formatters says that:
>  Emacs’s clojure-mode by default will format the code exactly as outlined in the guide.

That's alright and I do use Spacemacs. But there is some kind of mismatch between the formatting that is provided by the environment that I configured using Conjure.

I want to know whether I misconfigured something or is it that Fennel REPL that starts by default is used to format the code. Or maybe it's something else.

For instance this code snippet is idented by one space in Spacemacs but it's idented by two spaces in Conjure:
```
(Thread/setDefaultUncaughtExceptionHandler
 (reify Thread$UncaughtExceptionHandler ;; One space in Spacemacs
   (uncaughtException [_ thread ex]
     "do panic here")))

(Thread/setDefaultUncaughtExceptionHandler
  (reify Thread$UncaughtExceptionHandler ;; Two spaces in Nvim that uses Conjure
    (uncaughtException [_ thread ex]
      "do panic here")))
```
And this code is also sometimes formatted differently:
```
(inc  ;; nvim
  1
  2)
(inc  ;; spacemacs
 1
 2)

(let [] ;; let is consistent on both
  1
  2)

(inc 1 ;; this is consistent on both too
     2
     3)
```

Let's consider these code snippets (taken from https://learnxinyminutes.com/docs/clojure/):
```
(->  
 {:a 1 :b 2}  ;; One space in Spacemacs
 (assoc :c 3) ;=> (assoc {:a 1 :b 2} :c 3)
 (dissoc :b)) ;=> (dissoc (assoc {:a 1 :b 2} :c 3) :b)

(->  
  {:a 1 :b 2}  ;; Two spaces in Nvim
  (assoc :c 3) ;=> (assoc {:a 1 :b 2} :c 3)
  (dissoc :b)) ;=> (dissoc (assoc {:a 1 :b 2} :c 3) :b)
```

This one looks the same in both editors: 
```
(let [name "Urkel"]
  (print "Saying hello to " name)
  (str "Hello " name)) ; => "Hello Urkel" (prints "Saying hello to Urkel")
```

I remember this to be an old problem and I had problems when in one of my previous jobs I tried to use Spacemacs and the other guys used IntelliJ. 
Is this some kind of bad config on my part? How do I even configure it to be consistent? 
It also doesn't look at `.editorconfig` files on Spacemacs because the formatting is somehow hardcoded.
And that means that if at least somebody uses Emacs then there is no way to customize.

**Comment by daveyarwood** [comment]
I don't think this is specific to Conjure, but a general inconsistency with the way that Clojure code is indented by default in Vim vs. Emacs. The trouble is that there doesn't seem to be a clear agreement either way in the Clojure community. Even though the style guide says to indent by 1 space (unless it's one of many special case exceptions like `let`, `when`, etc.), I've heard many Clojure programmers argue that "always indent by 2 space" is simpler and easier to implement (because you don't have to account for all of the exceptions to the rule).

**Comment by daveyarwood** [comment]
There has been a lot of discussion about this over the years, including in this open issue from 2016: https://github.com/bbatsov/clojure-style-guide/issues/126

I don't want to re-hash or continue that argument here -- probably best to weigh in on the issue if there are any additional thoughts.

Anyway, if you want to make Vim behave like Emacs in this regard, I'm sure there is a way to do it and I don't think Conjure will interfere because I don't believe Conjure does anything special with regards to indentation (am I right, @Olical ?)

**Comment by Invertisment** [comment]
I was suggested to use `zprint` tool and I'm currently trying to remap my `equalprg` to run it correctly. I'll paste the result here.

This is the thread where I was suggested to use it:
https://clojurians.slack.com/archives/C03S1KBA2/p1657549069204999

**Comment by Invertisment** [comment]
Pretty rough escaping but I did it.
This could be added to your `.vimrc` file:
`autocmd FileType clojure set equalprg=zprint\ \'{:search-config?\ true}\'`

And after adding it you will be able to use `=` command normally and it will format using `zprint` tool.

What this additional option allows to do is to put `.zprintrc` file into your project's root and have project-specific Clojure formatting.

**Comment by practicalli-john** [comment]
The indentation different typically reduces down to if something is a list (1 indent) or an argument (2 indent).  The main format tools (cljfmt, cljstyle and zprint) allow this to be defined.

Closure LSP is available for most Closure aware editors and uses cljfmt to manage style formatting, so is a common candidate for using in teams with a variety of editors.

I use both neoVim and Emacs with LSP for consistent formatting when typing.  I also use cljstyle on the command line and as a GitHub action, as it produces the same formatting.
