### ISSUE TITLE
Cannot set configuration variables to nil

### ISSUE THREAD

**Issue by agorgl** [Olical/conjure#381]
When setting any configuration variable to nil as instructed from the helper doc: https://github.com/Olical/conjure/blob/2e7f449d06753f2996e186954e96afc60edd5862/doc/conjure.txt#L510

Then the configuration variable still gets overwritten with the default variable.

POC setup:
```
  use {
    'Olical/conjure',
    config = function() 
      vim.g['conjure#completion#omnifunc'] = nil
      vim.g['conjure#client#clojure#nrepl#mapping#refresh_changed'] = nil
      vim.g['conjure#client#clojure#nrepl#mapping#refresh_all'] = nil
      vim.g['conjure#client#clojure#nrepl#mapping#refresh_clear'] = nil
    end
  }
```
Executing `:lua print(vim.g['conjure#completion#omnifunc'])` (or any other configuration set to nil per se above) results in `ConjureOmnifunc` (the relevant default value).

This is caused by the nil check here:
https://github.com/Olical/conjure/blob/2e7f449d06753f2996e186954e96afc60edd5862/fnl/conjure/config.fnl#L45

I believe having the option to unset some configuration values is crucial, because this would allow to remove any conflicting keybindings and in this example, leaving the omnifunc to the relevant lsp handler.

**Comment by agorgl** [comment]
I suppose the only way to support `nil` configuration values is by supporting `vim.NIL` because lua treats `nil` the same as missing key according to this: https://neovim.io/doc/user/lua.html#vim.NIL

**Comment by Olical** [comment]
So the way I've got around this so far is to set things you don't want (omnifunc, mappings) to `v:false` instead of `nil` etc, I admit the docs in `:h conjure` said `nil` for omnifunc which is incorrect, I've just fixed that.

The mappings however do say you should use `v:false` although it is burided in `:h conjure` which isn't super clear. Supporting `v:nil` across the board will be a little tricky but possible. Your PR is maybe a solution although it involves a single pass at startup to transform `vim.NIL` (a truthy value!) into `nil` (a falsy value!).

That single pass at startup and reliance on it to transform the value will maybe cause weird issues for people down the line where they thing `v:null` works but then if they set it too late suddenly Conjure will enable things they thought were disabled because `vim.NULL` is true in Lua.

So I'd like to avoid that transform is possible by discouraging people from using `v:null` at all and instead using `v:false` which IS falsy in Lua by default because it's converted to the lua false value. It is also possible to store a false inside a table where a nil isn't.

So, my answer is: I think we should stick to recommending and using `v:false` to signify "turn this off" for now for mappings and omnicompletion etc. I've updated the help text on omnicomplete to recommend `v:false` too.

**Comment by agorgl** [comment]
Thank you, setting my options to `v:false` seems to work fine for now.
I still believe that `false` is not a semantically correct representation for unset config variables and is somewhat confusing, although explicitly specifying it in the documentation kinda helps a bit.

You can close this for now (along with its respective PR) if you have no further plans for allowing that kind of transformations.

PS. Thank you for this amazing plugin!

**Comment by Olical** [comment]
I do agree it's not semantically correct but for my purposes it's "good enough". I mostly like it because `v:false` becomes lua `false` which is... falsey... so it works great in conditionals where I check for config.

I will consider moving support to `v:null` at some point, but it'll be work across the board to make sure all code handles that case. Because `v:null` becomes a truethy value in lua which will break a LOT of if statements. I'll need to make sure I catch every one or risk introducing quite a few bugs.

For now though, I'll close this but keep the change in mind, I agree it's right, just time and there's bigger things to fix at the moment 😄 thank you for the investigation, work and suggestion!
