### ISSUE TITLE
extract.prompt does not work in Conjure interactive evals

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#389]
Calls `(extract.prompt "")` yields `':silent! call repeat#set(",e", 1)\n'`

_Originally posted by @glyh in https://github.com/Olical/conjure/issues/388#issuecomment-1207226305_

**Comment by glyh** [comment]
I guess this has something to do with `mapping.buf`

**Comment by glyh** [comment]
OK this is must have something to do with other plugins since I can't reproduce it with a minimal config.

**Comment by glyh** [comment]
Although the above method works, evaluating this won't work:
```fennel
 ((. (require "conjure.extract") :prompt) Input required: ")
```
So this must be an issue in conjure.

**Comment by Olical** [comment]
I think I've gone through this with someone else in discord or slack recently, this is something to do with how Aniseed has to wrap  your calls in evals to capture the stdout and ensure your eval happens in the right context.

If you wrap your call to the prompt code in a `vim.schedule` it should work fine because it happens in some other tick of the libuv system inside Neovim without Aniseed's wrapping. I _think_ that's it anyway, maybe there's a code change we could make to `prompt` to make it work in or outside of Aniseed's interactive wrapping code but I'm not sure.

**Comment by glyh** [comment]
Is this how I supposed to be writing?
```fennel
(defn prompt-promised [prefix]
  (let [promise (require "conjure.promise")
        p (promise.new)
        del (promise.deliver-fn p)]
    (vim.schedule (fn [] (del ((. (require "conjure.extract") :prompt) prefix))))
    (promise.await p)
    (promise.close p)))

(prompt-promised "hey")
```
It didn't fix the problem though...

**Comment by Olical** [comment]
So do you still see the input request printed instead of executed? Or nothing happened? Because at a glance that looks pretty good to me. I'll try to look at somehow getting the prompt working in interactive evals soon, it should work outside of Conjure's interactive eval wrapping. Which is why I recommended wrapping in vim.schedule since that then executes outside of Conjure's callstack.

I wasn't thinking about bringing the result back into the original callstack with the promise stuff though, I was thinking you just make the call async and have a callback function that gets called with your result. YMMV with Conjure's promise code, I'm trying to make some magic work in a VM that was never intended to support those sorts of things. It may not work for all scenarios especially where there are calls out to some deep Vim C code involved.

**Comment by glyh** [comment]
I still see `':silent! call repeat#set(",e", 1)\n'`

**Comment by Olical** [comment]
Ah, it's vim-repeat integration. I have a hunch, I think I can maybe call repeat BEFORE the eval goes through to fix this. Maybe. Will try it in a sec.

**Comment by Olical** [comment]
Seems fixed for me on develop now!

**Comment by glyh** [comment]
Yaeah it works for me now.

**Comment by Olical** [comment]
This is to do with the vim-repeat integration but the fix broke more things so I'll dig into this and try to fix it properly soon. Will require a fair bit of refactoring, possibly #390 which will break backwards Neovim compatibility but make this a LOT easier to get right.

Most Conjure weirdness and bugs are caused at the VimL boundaries, the more I can use proper Lua function APIs that support function callbacks etc the easier it'll be to get this right and still keep the code readable.

**Comment by glyh** [comment]
Is this fixed? I just pulled the develop branch and try to evaluate `io.read()`, and I still got this:
```
':silent! call repeat#set(",e", 1)\n'
```

**Comment by Olical** [comment]
Nope, not fixed, I didn't mean for this to get closed and it was automated, sorry about that. I need to update more mapping code all over the codebase, will get back to that next since I'm done playing whackamole with some other issues.

**Comment by Olical** [comment]
Should be fixed now! Please re-open if not.

**Comment by glyh** [comment]
It is working. Nice job Olical!
