### ISSUE TITLE
Improve user feedback when the client is asking for more user input.

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#392]
<del>E.g.
Say I first evaluate `"asd`, which is invalid fennel code. It yields `nil`.
And then whatever I evaluate, it always response `nil`.</del>

In fennel's aniseed client, when user's input is not finished, the evaluation returns nil, which make it confusing for users. It would be nice if there's some hint in the log buffer to distinguish it from a call that returns nil.

**Comment by Olical** [comment]
Do you mean the fennel stdio client? That doesn't look like an error or invalid code to me, that looks like an open string that the REPL keeps interpreting as more string until you get to a closing quote.

The `nil` you're seeing may just be a default output from the fennel client that's trying to interpret the lack of response from the REPL. It should really print "no response" or something different, the `nil` is sort of masking the issue that Conjure is sending code to the REPL but nothing is happening. I think.

So the REPL isn't dead, you've just dropped it into a string and not closed it which Conjure can't tell. It also has no idea that restarting the REPL helps in that case since it's not dead. I think it _would_ restart the REPL if the process had died although I'm not sure of that.

**Comment by glyh** [comment]
No, it's the aniseed client.

**Comment by Olical** [comment]
Ah, same problem still applies though, you've sent `"` to the Fennel REPL and not closed it. I don't think there's any way for me to detect or know that right now, this is a flaw in the Fennel REPL (the official one I'm wrapping and using). It doesn't isolate evals like nREPL does where `"` would be a syntax error. Instead the Fennel REPL just takes an infinite stream of code and spits out values as they happen, so the API just doesn't allow me to detect this or do anything about it I'm afraid.

**Comment by glyh** [comment]
Okay, let me rename this issue as an enhancement.

**Comment by Olical** [comment]
I can't do this automatically because I might end up resetting the REPL when you didn't want me to, but I've already got tools to get around this (`<prefix>rr` and `<prefix>ra`) so I've changed the default `nil` result to instead warn you that the REPL isn't giving us any results and that you should check the relevant `:help` for information on resetting the REPL if you think you need to.

I don't think I want to automatically reset the REPL and clear your state for the buffer if we encounter no results though. That seems risky and potentially bad and yet another thing to document, configure, explain and coax people to use or not use depending on their scenario. Hopefully better self documentation in this scenario will be enough.

**Comment by Olical** [comment]
Closing for now since I've tried to make this self documenting. But if someone can find a way to reliably get the Fennel REPL to kind of hit EOF and end the eval, maybe print a syntax error, then be ready for the next input I'm all ears.
