### ISSUE TITLE
Problems in combination with FZF

### ISSUE THREAD

**Issue by iGEL** [Olical/conjure#398]
I run into problems with v4.36.0 of Conjure in combination with fzf. Unfortunately I don't know too much about debugging neovim, but I'll try my best to provide at least some info.

When I open the file search (space t with the config below) and select a clojure file and press ctrl+t or ctrl-v, I get this error:

```
Error executing vim.schedule lua callback: /home/igel/tmp/conjure/conjure/lua/conjure/process.lua:79: Invalid buffer id: 2
stack traceback:
        [C]: in function 'win_set_buf'
        /home/igel/tmp/conjure/conjure/lua/conjure/process.lua:79: in function 'execute'
        ...jure/conjure/lua/conjure/client/clojure/nrepl/action.lua:71: in function <...jure/conjure/lua/conjure/client/clojure/nrepl/action.lua:64>
```

```
vi --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Config:
```
set nocompatible

filetype off                   " required!

call plug#begin('~/tmp/conjure')

Plug 'Olical/conjure'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" All of your # Plugs must be added before the following line
call plug#end()

filetype plugin indent on    " required
let mapleader=" "
let maplocalleader=" "

let $FZF_DEFAULT_COMMAND = 'rg --files'

nnoremap <silent> <space>t :Files<CR>

" Additional mapping for buffer search
nnoremap <silent> <space>b :Buffers<cr>
```

I think, it broke with 44a2f60988253742b1241c32631591cd575d4020

**Comment by iGEL** [comment]
Actually, with my normal config, I get a different error I just realized:

```
Error detected while processing function 17[30]..<SNR>48_callback:
line   23:
Vim(lua):E5108: Error executing lua ...lugged/conjure/lua/conjure/client/clojure/nrepl/init.lua:127: attempt to call field 'buf_create_user_command' (a nil value)^@stack traceback:^@^I...lugged/conjure/lua/conjure/client/clojure/nrepl/init.lua:127: in function 'on-filetype'
^@^I[string ":lua"]:1: in main chunk
Press ENTER or type command to continue
Error executing vim.schedule lua callback: /home/igel/.vim/plugged/conjure/lua/conjure/process.lua:79: Invalid buffer id: 2
stack traceback:
        [C]: in function 'win_set_buf'
        /home/igel/.vim/plugged/conjure/lua/conjure/process.lua:79: in function 'execute'
        ...gged/conjure/lua/conjure/client/clojure/nrepl/action.lua:71: in function <...gged/conjure/lua/conjure/client/clojure/nrepl/action.lua:64>
```

**Comment by Olical** [comment]
Ah this is because I've started to use some features of Neovim that are only in version >0.6.1. Possibly 0.7 at a minimum although I'm not sure off the top of my head. These changes are breaking but they're using core features that I've had to hack around up until now.

Those hacks, although backwards compatible, have their own bugs that are very hard to avoid. Changing to these newer core APIs (which allow me to pass Lua functions as callbacks instead of hacking together VimL that calls Lua later by name (scary!)) means users will have to update.

This one function call that you're running into was the first of these changes, there are more on develop but I'll be putting warnings in Conjure and the README about minimum Neovim versions going forward.

So you'll have to update to the latest stable Neovim (I'll never depend on nightly features or things that JUST came out) or pin your Conjure version behind a little bit. Sorry about the issue, it's not an easy decision to introduce breaking changes but I need to start using these APIs, they make Conjure's code SO much simpler and robust.

I also have a bunch of code in Conjure just to deal with breaking changes in Neovim! So if I can ensure people update to 0.7+ I can delete a bunch of backwards compatible code and simplify things further 🎉 

My apologies if this is inconvenient for your chosen OS! I know some package managers usually lag behind by months 😢

**Comment by Olical** [comment]
I'm going to close this with the assumption that updating Neovim will fix it because I'm struggling to keep support going for older versions of Neovim as they introduce breaking changes slowly. Please reopen and let me know if updating Neovim doesn't help.
