### ISSUE TITLE
[FR] Call main function when evaluating file in Rust evcxr

### ISSUE THREAD

**Issue by glyh** [Olical/conjure#399]
As title.

I think it would be more ergonomic to just call the main function and ask parmeters of it to user if necessary.

BTW, rust client seems to print a lot of stuffs on the REPL as comments, I personally don't like this approach. We could improve it maybe via writing a customized version of REPL based on some core evcxr libraries.

**Comment by Olical** [comment]
@rafaeldelboni would love your opinion on this one too! I appreciate that you may just not know about this sort of thing either.

**Comment by rafaeldelboni** [comment]
Is possible to call the main function via the stdio interface? If not that would need a complete rewrite of the integration, but I wouldn't mind of is there a good documentation about how to do this.

About the customized repl based on evcxr libraries, I totally would go using nrepl protocol instead of stdio like the current one if I was going to make one.

And I'm sorry if I used/integrated anything wrong, I just had the idea of integrating a rust repl while I was studying rust after years working with clojure.

**Comment by Olical** [comment]
> And I'm sorry if I used/integrated anything wrong, I just had the idea of integrating a rust repl while I was studying rust after years working with clojure.

Oh no no, you did great, I think anything is better than nothing, I don't expect every client to do everything everyone wants ever. I only roped you in here for your input since you have the most context... compared to me especially!

**Comment by glyh** [comment]
Close in favor of more generalized #508 . That one is closed as well because it should be implement in LSP/DAP. We can keep conjure simple by not implementing this feature.
