### ISSUE TITLE
Sometimes "evaluate current form" result stops being printed into log

### ISSUE THREAD

**Issue by Invertisment** [Olical/conjure#402]
I'm not sure how it happens but when I run tests (via my own nREPL middleware plugin) and then reevaluate the form before the tests pass then the output from Conjure gets lost.
i.e. I can't see the output of my evaluated expressions and instead it reevaluates the namespace, I think.

Do you think this is a problem on Conjure's side or nREPL's side?

If I kill the buffer and reopen it then it works again.

**Comment by Invertisment** [comment]
What's really weird is that `ConjureEvalVisual` always works regardless. I think this is a new bug.

**Comment by Olical** [comment]
Possibly just this: https://github.com/Olical/conjure/issues/367

Which would mean you're using tree sitter + the currently latest released version of Conjure. If so, could you try the `develop` branch? I need to release that since it's full of fixes, I just haven't had time this weekend.

**Comment by Invertisment** [comment]
I have disabled treesitter just a moment ago and it doesn't occur

**Comment by Olical** [comment]
Yes, if you try the develop branch that bug has been fixed. It's actually when you use tree sitter but disable tree sitter highlighting.

It turns out if you want to use the tree sitter API you need to remember to call a "refresh" function every single time before you access the data structure because if the user of TS doesn't have highlighting enabled then the tree is not refreshed on file change.

That is fixed on `develop` so we call the refresh function before each access now.

**Comment by Invertisment** [comment]
So will this bug occur for all other nvim plugins too? Why is this the case with this plugin? Should I expect other plugins to break for other languages?

**Comment by Olical** [comment]
Yes if they have the same bug and read the tree sitter tree regularly. They
will run into the exact same issue. There probably aren't that many plugins
out there using the tree sitter API like this yet though.

**Comment by Olical** [comment]
Released the fix.
