### ISSUE TITLE
[feature] eval with snippet

### ISSUE THREAD

**Issue by nouun** [Olical/conjure#418]
It would be nice to have the ability to be able to create key binds which evaluate the current form with a snippet, for example `(render $current-form)` which would call `render` with the current form.

**Comment by Olical** [comment]
I won't be adding this as a new feature since every new feature is another burden of maintenance (and it's already kinda too much!) but I can point you in the right direction to do it yourself since all of the pieces are already there and easily callable.

If your config is Lua you can require `conjure.eval` and `conjure.extract` which contains all of the functions you need to rip code out of the buffer, wrap it in any way you want then send it off for eval. There's also the `ConjureEval` command which evals whatever you send it, so you could have a mapping that rips code out of the buffer (either your own or using `conjure.extract`) then pass it to `ConjureEval`.

Some examples of requiring and using Conjure internals here https://github.com/Olical/conjure/wiki/Using-Conjure-programatically-(API)

If you're really stuck though I can probably knock together an example, much easier to do in Lua, writing it in Vim Script becomes a fiddly trial and error because I can't ever remember all of the language rules (hence only writing nvim stuff in Lua).

**Comment by Olical** [comment]
That example I linked is almost exactly what you want, you just need to require `conjure.extract` and use the `(extract.form {})` function from there to get the current form under the cursor. You'll have to read some Fennel to find the functions and how they work I'm afraid, but they're mostly easy to follow I think.

See https://github.com/Olical/conjure/blob/master/fnl/conjure/mapping.fnl for all of the current mappings and what they call to do the existing parts of Conjure.

You just need to take what I have in the example, add some current form extraction call and then point a nvim mapping at it.

**Comment by nouun** [comment]
Thank you so much! I tried looking around the Conjure docs inside nvim but didn't see the API docs, that's exactly what I need.

**Comment by Olical** [comment]
Yeah sorry I only have one doc on that. You kinda have to just dig into the Conjure internals to get creative, but all of the wiring is exposed and you're welcome to call it, I rarely change fundamentals like that at all. I wouldn't say it's a stable public API but it hasn't really changed since I created it.

I'm planning on making some more YouTube videos touring the internals of the codebase for tinkerers and client contributors / general Conjure contributors. Maybe that'll be a useful source for this sort of thing in the future.

I'd refer to reaching into Conjure and using / changing / enhancing things as "modding" personally. I think that's a good term for it.

**Comment by Olical** [comment]
And hey, if you like your changes and think others could benefit from them, feel free to make it into a standalone plugin that piggiebacks off Conjure. I'd like to build a central doc that leads people to the wider Conjure Cinematic Universe of plugins that add things like this.

That way I don't need to add and maintain every feature conceivable, but I can keep improving the core that so many people's cool ideas are built on.
