### ISSUE TITLE
Question: how to disable default mapping

### ISSUE THREAD

**Issue by illia-danko** [Olical/conjure#448]
Hey there,
 and thank you for the awesome plug which makes enjoyable editing lisp code in neovim.
Found some issue regrading overwriting of some existing user keymapping with conjure plugin's ones. Skimming documentation didn't help me (maybe overlooked this), but I want to give a full control of making my own mapping, however changing every conjure's keymap is tedious and fragile (I'm happy with some of them such as, <localleader>e.., but not all of them).
So my workaround is something like `vim.g["conjure#mapping#prefix"] = ""` but not sure it is the right way doing a such thing. And maybe it's worth to mention somewhere in docs how to turn off default mapping completely.
Thank you.

**Comment by Olical** [comment]
Hey, that's done by setting them to `v:false` which is the VimL way of
writing false. If you're writing Lua you can set them to false. I can't use
nil because there's no way to distinguish nil from no user configuration,
so nil looks like you haven't set anything so I should default it. False on
the other hand is detectable and should turn the mapping off. This should
be in `:h conjure`, if not that's an issue.
