### ISSUE TITLE
Completely disable a client

### ISSUE THREAD

**Issue by LordMZTE** [Olical/conjure#472]
How can I completely disable a client? I don't want conjure to be active in Rust files. This is what I've tried so far (in fennel):

```fennel
(tset vim :g "conjure#filetypes" [:clojure
                                  :fennel
                                  :racket
                                  :scheme
                                  :lua
                                  :lisp
                                  :python])
```

This list contains all conjure clients except `rust`.

However, when I open a rust file, then `((. (require :conjure.client) :get))` returns a client, and not `nil`.

**Comment by Olical** [comment]
Are you setting this before Conjure loads at all? I have a feeling (can't remember exactly right now) that you need to set this option before Conjure defines it's autocmds at startup, if you set this afterwards the autocmds are already there and updating the config won't dynamically change them. This is working for other users, so I suspect it's a timing thing that needs to either be improved or better documented.

**Comment by kaepr** [comment]
I had a similar issue. Setting filetypes before the plugins loads fixed it for me.

**Comment by LordMZTE** [comment]
I don't think so. I have this in my packer config:
```fennel
(use {1 :Olical/conjure :setup #(require :my-conjure-config-module)})
```
According to the packer docs, this will make my config run before plugin initialization. I don't know how to make sure this is actually the case, but I know that it does run.

With this config in place and my above config being the `my-conjure-config-module` module, this still loads the rust client.

**Comment by Olical** [comment]
> However, when I open a rust file, then ((. (require :conjure.client) :get)) returns a client, and not nil.

@LordMZTE so that may well still return a client even if it hasn't been loaded, the act of getting it actually does the loading. Do the eval mappings work before you do that?

If they don't work, the client hasn't been loaded because the `filetypes` option dictates which filetypes trigger a client setup function. If you remove a filetype from there then the autocmd won't be set up and triggered. If you _manually_ look up a client (like the snippet you sent) then it will check what client it _would_ have loaded for that filetype and load it anyway because you manually invoked it.

So you might have to also set `g:conjure#filetype#rust = v:false` which would mean you've disabled the filetype autocmd startup _and_ removed the lookup if there's a manual invocation of some kind.

**Comment by LordMZTE** [comment]
Seems like that did it! Thanks!

**Comment by p-h** [comment]
Are you sure this issue is resolved? Is explicitly disabling every client that you don't use one-by-one and adding new configuration to disable additional ones if support for new clients gets added to conjure the intended behavior?

**Comment by Olical** [comment]
Hm a fair point, really just `g:conjure#filetypes` should be good enough.

**Comment by p-h** [comment]
And it actually seems to work. Just after submitting my comment I realized I had an error in my init.lua. But you answered so quickly that I was unable to delete my now embarrassing comment in time 😅 . Sorry, about that.
