### ISSUE TITLE
Support for Gerbil Scheme

### ISSUE THREAD

**Issue by chiefnoah** [Olical/conjure#485]
I'm attempting to add support for Gerbil scheme (a wrapper around Gambit), but am seeing some really bizarre behavior from Conjure. I've created a new folder in `clients/` called `gerbil` with a `stdio.fnl` file in it largely copied from `scheme`. There's some peculiarities with the raw scheme backend, as it seems to look for `.scm` files, which aren't typically used for Gerbil which uses `.ss` files.

I'm testing with a simple Gerbil file:
```scheme
(export main)
(def (main . args)
    (displayln "Hello"))
```
and receive this error:
```
E5108: Error executing lua: Vim:Error executing Lua callback: Conjure client '' doesn't support function: eval-file
stack traceback:
...
```
I've elided the stacktrace, as it has nothing helpful in it. It seems Conjure is not detecting which backend it should use, it's very not clear how it even selects the backend. Assistance with this would be appreciated, otherwise the next best thing is some documentation.

**Comment by russtoku** [comment]
To have Conjure associate `.ss` files to your Gerbil Scheme client, set the buffer suffix to `.ss` in your `client/gerbil/stdio.fnl` file like so:
```
(def buf-suffix ".ss")
```

If you haven't already, you should probably set this so that the configuration for your Gerbil Scheme client is set up correctly with Conjure:
```
(def- cfg (config.get-in-fn [:client :gerbil :stdio]))
```

Have you read https://github.com/Olical/conjure/wiki/Client-features or `:h conjure-clients`? Either should be helpful with creating a new Conjure language client or understanding an existing one. I took me a while to get a tiny bit of understanding but they do help.

**Comment by chiefnoah** [comment]
I've already done all of that, which is why I'm so confused. I'll take another look shortly. Even though it's technically a Scheme, is there any appetite for accepting PRs that add this in?

**Comment by chiefnoah** [comment]
So the issue with this was the filetype was matching (it was `scheme`), but the suffix did *not*, as Gerbil tends to use `.ss` files. I added that to the global config and submitted a PR. Thanks for the assistance!

**Comment by Olical** [comment]
Merged! Thanks for finding and addressing that.
