### ISSUE TITLE
CommonLisp: add command to start swank server.

### ISSUE THREAD

**Issue by LordMZTE** [Olical/conjure#493]
It would be great if conjure could start a swank server for CommonLisp so this doesn't need to be done by the user. This essentially just equates to running `ros run --eval '(ql:quickload :swank)' --eval '(swank:create-server :dont-close t)'`.

**Comment by Olical** [comment]
I think this is erring on the territory of how I explicitly decided to not start any Clojure REPLs (other than babashka) because there's more REPL combinations and protocols than there are atoms in the observable universe.

I guess this is different because they all speak the same language (swank? I still don't really grok CL and it's tooling) so it's not like saying "hey Conjure, handle every intricacy of every possible Clojure and ClojureScript REPL and transport out there and keep up with all changes in the ecosystem". That idea scared me so I just leave it up to the user to handle however they want.

Just to put my initial fear reaction into perspective 😅  Also what's ros? A package manager? Those assumptions about "you must have X installed" will need to be well documented and more code will need to be added to catch all the cases where certain things aren't set up right with appropriate error messaging 🤔 

Also if this should automatically start or not is an interesting conundrum.

I personally like https://github.com/clojure-vim/vim-jack-in - the whole REPL problem is distributed to a different repo with a tight focus, you can still run the REPL inside Neovim, it's just that Conjure doesn't need to know about it.

So considering a new project that wraps up a bunch of CL REPL patterns into nice easy to run commands might also be a decent approach.

**Comment by LordMZTE** [comment]
I do understand your point a lot better now after having learnt to actually use CL. Yes, roswell is a package manager, it's pretty much ubiquitous, but there still are a lot of combinations as you stated. I've also gotten used to start a REPL in a seperate terminal, which brings the advantage of being able to use it to evaluate statements in the context of the code.
