### ISSUE TITLE
Connect to repl-listen with cljsbuild

### ISSUE THREAD

**Issue by somecho** [Olical/conjure#496]
Hello! First of all, thanks for Conjure. I really enjoy using it.

My issue: I have a leiningen with a cljsbuild plugin and I'm following the instruction here https://github.com/emezeske/lein-cljsbuild/blob/1.1.8/doc/REPL.md#repl-listen to start a repl. I want to then connect to this repl by using `:ClojureConnect 9000`. It seems to connect, but evaluating expressions does nothing.

I have previously tried using shadow-cljs's browser-repl, but evaluating things like `(js/console-log "hello")` leads to error messages like `no such namespace: js`.

**Comment by Olical** [comment]
Small heads up that the docs that page links to now points to https://clojurescript.org/guides/quick-start - the Clojure CLI now comes with ClojureScript REPL tooling inside of it I think.

I'm pretty sure I know what's going on here:

 * You're starting a ClojureScript REPL, that's actually a _Clojure_ REPL with a ClojureScript one inside of it.
 * When Conjure connects to the nREPL port it's still talking Clojure, it's not talking ClojureScript with your browser yet.
 * The next step you normally need is sometimes called "piggiebacking" or in Shadow CLJS, shadow select.
 * When you "piggieback" you upgrade the Clojure nREPL connection you have so it forwards the code to the browser and starts speaking ClojureScript.

So I think you have `conjure -> clojure repl` and what you need is the piggieback step which gets you `conjure -> clojure repl -> clojurescript in browser`.

Here's a gist explaining how to set up a figwheel REPL, connect and piggieback: https://gist.github.com/pyrmont/73d10c74d14f26772fd276c38ee3490d

And here's my example on doing this with shadow-cljs: https://github.com/Olical/conjure/wiki/Quick-start:-ClojureScript-(shadow-cljs)

Looking at https://clojurescript.org/reference/repl I think what you want is this code for the piggieback with this browser REPL (not figwheel or shadow, but the built in one you're using):

```clojure
(require '[cljs.repl :as repl])
(require '[cljs.repl.browser :as browser])  ;; require the browser implementation of IJavaScriptEnv
(def env (browser/repl-env)) ;; create a new environment
(repl/repl env) ;; start the REPL
```

Sorry that this are of ClojureScript is so fiddly, I personally found that shadow-cljs (or figwheel!) were the best options, they provide a lot of tooling and opinions to get you going. I'd personally recommend shadow since Conjure has integration for that (linked above).

I hope some of this points you in the right direction and helps out!

**Comment by somecho** [comment]
Thank you so much for taking the time to look into this and explain it to me. It has not gone to waste because I have figured it out! Here are the steps I took to make it work without Shadow or Figwheel. 

### Add piggieback to project.clj

```edn
(defproject cljs-repl "0.1.0
  :dependencies [[org.clojure/clojure "1.11.1"]
                 [org.clojure/clojurescript "1.11.60"]
                 [cider/piggieback "0.5.3"]]
  :repl-options {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]})
```

### Start Lein repl
`:Lein` in Neovim 

### Connect to the Lein repl
`:ConjureConnect PORT`

### Start CLJS repl INSIDE Lein repl
```
cljs-repl.core=> (require 'cljs.repl.browser)
nil
cljs-repl.core=> (cider.piggieback/cljs-repl (cljs.repl.browser/repl-env))
```

Now it will prompt `Waiting for browser to connect to http://localhost:9000 ...` and I just open it in the browser. 

### Evaluating now works
Now when I evaluate something like `(js/alert "hello")`, the browser responds and the eval log buffer inside neovim also shows the correct output of the evaluation (which is `nil`). 

I hope this helps anyone trying to figure out a way to do things some other way than the Shadow or the Figwheel way! And also thanks again Oliver for pointing me in the right direction.
