### ISSUE TITLE
Getting conjure to work with snd/s7

### ISSUE THREAD

**Issue by kflak** [Olical/conjure#507]
Hi,

This might very well be too esoteric, but I'm trying to get conjure to work with [snd](https://ccrma.stanford.edu/software/snd/snd/snd.html), a wave editor for linux that listens on stdin and sends out to stdout, running a dialect of scheme called s7. At the moment I am able to send a single command to `snd`, but I don't get anything back, so I suspect something is stuck in the pipe from `snd`  to the conjure repl. As far as I've been able to assert there is nothing fishy being sent out from `snd`, other than the last return value.

My config for this, using `lazy.nvim`:

```
    {
        'Olical/conjure',
        init = function()
            vim.g['conjure#client#scheme#stdio#command'] = 'snd'
            vim.g['client#scheme#stdio#value_prefix_pattern'] = false
            vim.g['conjure#client#scheme#stdio#prompt_pattern'] = '>'
        end,
    },
```
Any hint of what might be getting in the way is much appreciated!

**Comment by Olical** [comment]
Would you be able to run this with `let g:conjure#debug = v:true` and share the Conjure log buffer output here? That'll show us exactly what was sent and received. This might be yet another good candidate for https://github.com/Olical/conjure/discussions/500 if it's proving too tricky with today's tools.

I'm in my last week at my current job and have ~2 weeks off coming up. So love for stdio will be one of the things I try to focus on in that time.

**Comment by Olical** [comment]
The issue may well just be the prompt pattern (which I aim to completely do away with in my rewrite in favour of something more contextual and programmable)

**Comment by kflak** [comment]
Thanks for the debug tip!

Seems the problem is mostly my (complete) inexperience with scheme/lisp and associated repls. And it also seems that `snd` works mostly with one-shot commands. Still wrapping my head around that.

Running this chunk of code:
```
(begin
 (open-sound "/home/kf/xylophone.wav")
 (scale-channel 0.1)
 (save-sound-as "/home/kf/xylophone-scaled-1.wav")
 )
```
produces this log:
```
; Sponsored by @Aljendro ❤
; --------------------------------------------------------------------------------
; snd (started)
; --------------------------------------------------------------------------------
; eval (current-form): (begin (open-sound "/home/kf/xylophone.wav"...
; debug: send
"(begin
 (open-sound \"/home/kf/xylophone.wav\")
 (scale-channel 0.1)
 (save-sound-as \"/home/kf/xylophone-scaled-1.wav\")
 )
"
; debug: receive
"out" nil "\"/home/kf/xylophone-scaled-1.wav\"
"
; debug: receive
"out"
; debug: receive
"err"
; --------------------------------------------------------------------------------
; snd (stopped)
```

The `; debug: receive` only comes in after I close `snd` manually, which strengthens my suspicion that this is indeed designed as a one-shot kind of a program.

**Comment by kflak** [comment]
Digging in a bit further it seems that the prompt pattern is not, in fact, necessary.  The default works. However, I do need to set the value_prefix_pattern to `false` .

**Comment by kflak** [comment]
After a reasonable amount of testing and asking on the mailinglist there seems to be no way to set up an external repl via stdin. There's an emacs plugin that does something like this, but nobody seems to understand how it works its magic. So I would be happy with a solution where I just fire off an EOF. How would I go about doing this?

**Comment by russtoku** [comment]
@kflak,

I've created a proof-of-concept snd-s7 client on the [dev-snd branch](https://github.com/russtoku/conjure/tree/dev-snd) of my fork of the Conjure repo.

Please try it out and see if it does what you need. If it's OK and moves you in the direction you want to go, I'll add some help docs and make a pull request.

I implemented and tested it with a `snd` program built for MacOS from the version 23.5 tarball from Sourceforge and without a gui so I'm hoping it will work for you.

I did find the Common Music mailing list a bit misleading and less than helpful. The `snd` and *S7* websites require a lot of head scratching to understand what's going. This presents a high barrier to entry but I think that's because the people in that community aren't programmers and system administrators and just want to get their music and research done.

I am intrigued by the possibilities of `snd` as a scriptable sound editor because I use Audacity a lot for tweaking audio from videos or sound recordings. Some day, I'll have to give it a go on my Linux box.

**Comment by kflak** [comment]
@russtoku Thank you thank you thank you!!! Running a couple of cursory tests, seems like you've nailed it.

Agree wholeheartedly that the docs feel more like a record of something the village elderlies put together to chronicle their ancient wisdom, mostly for the already initiated...

**Comment by Olical** [comment]
Amazing work @russtoku! If you're happy with the behaviour @kflak I'll be happy to merge a PR. As long as there's one happy user I tend to trust that the client is in a useable state and can be included 😄 even if I don't have practical knowledge about the tool/language.

**Comment by kflak** [comment]
So far it seems like it's working as expected. Very happy user here :-)

**Comment by russtoku** [comment]
Great news!
Before I make a PR, I'll have to make some changes so that the snd-s7 client isn't the one that handles Scheme files (*.scm) and provide some guidance for how to configure Neovim so that when you load up a Scheme file the snd-s7 client handles evaluations. This would be something like `:let g:conjure#filetype#scheme = "conjure.client.snd-s7.stdio"`.

**Comment by russtoku** [comment]
See pr #514 .
