### ISSUE TITLE
Other floating windows overlap HUD

### ISSUE THREAD

**Issue by flipsi** [Olical/conjure#529]
# Problem description

When using Conjure together with [context.vim](https://github.com/wellle/context.vim), the floating window of context.vim stays on top of the Conjure HUD floating window. 
A reasonable behavior would be the other way around - the short-lived HUD on top of the permanent context window.

# Details

As we know, floating windows can be controlled via the zindex (stacking order) option.

A short search in the codebases revealed that 
* [context.vim appears to not use the zindex option](https://github.com/search?q=repo%3Awellle%2Fcontext.vim%20zindex&type=code).
* [Conjure hardcodes zindex to 10](https://github.com/Olical/conjure/blob/58c46d1f4999679659a5918284b574c266a7ac83/fnl/conjure/log.fnl#L207), probably [because of _passive logging_](https://github.com/Olical/conjure/issues/321).

# Proposal

This is not the smartest solution for sure, but can we simply allow customizing the HUD zindex via some global var?

# Versions

NVIM v0.9.2
Conjure 58c46d1f4999679659a5918284b574c266a7ac83
context.vim 108644e146c864995288dee7dacf219267917ac1

**Comment by Olical** [comment]
Hey thanks for reporting this. I've added an option to control the zindex and lowered the HUD from 10 to 1 by default. This is on the `develop` branch so you can try it out there. We can't go negative with the zindex like you can in CSS for example, so we may need to set a positive zindex on context.vim in order to push it behind Conjure.

Or maybe just having Conjure's HUD set to a zindex of 1 is enough since the window is created AFTER the context.vim window?

**Comment by flipsi** [comment]
Sorry for my ridiculously late reply and necrobumping the issue...

But I just wanted to 
* let you know that the feature works great and
* thank you for adding it! A appreciate this very much! Keep on the great work!
