### ISSUE TITLE
How can I write a conjure client without aniseed?

### ISSUE THREAD

**Issue by Risto-Stevcev** [Olical/conjure#530]
I'm trying to write a nodejs stdio conjure client, but I'm getting blocked by the aniseed macros and I don't know how to proceed.
My current code is in this gist: https://gist.github.com/Risto-Stevcev/51b29b79b661caeee38341fa12365aa7

I'm using the newer [nfnl](https://github.com/Olical/nfnl) and it doesn't include the aniseed macros. I'm trying to avoid the need for them, but I think I'm running into errors with my `buf-suffix` and `comment-prefix` being local:

```
Error executing vim.schedule lua callback: ...risto/.local/share/nvim/lazy/conjure/lua/conjure/log.lua:499: attempt to concatenate a nil value
stack traceback:
        [builtin#19]: at 0x7fdc6bb64280
```

I also tried just installing aniseed, but I have no idea how to point to the aniseed macros. I tried `import-macros` and `include`, etc, and it says no module named `aniseed` found.

**Comment by Olical** [comment]
Hey there! Sorry for the mess, I need to migrate Conjure since nfnl should make it far easier for people to contribute.

You shouldn't need the Aniseed macros at all and your client will be relying on the compiled Lua output of Conjure, the macros are only there at compile time in the Conjure source. From your code's perspective they shouldn't exist and you shouldn't need them.

This error is because you're concatenating a `nil` with `..` in your calls to `conjure.log/append`. I recommend using `conjure.aniseed.string/join` to join strings together which will handle nils no problem. I personally would replace EVERY use of `..` with a call to my `join` function because `..` has been the source of MANY bug reports in the past where a nil slips through.

**Comment by Risto-Stevcev** [comment]
Thanks for the suggestion, the issue though is that line 499 in `conjure/lua/conjure/log.lua` -- it looks like it's because I have a [local definition of](https://gist.github.com/Risto-Stevcev/51b29b79b661caeee38341fa12365aa7#file-conjure-node-fnl-L28) `comment-prefix`. What do I need to do to fix it without using aniseed?

I tried poking around in the code but I'm not familiar enough with fennel/aniseed/lua/neovim-scripting to figure out how to set it. It looks like it needs a `tset`, looking at the macro definition [here](https://github.com/Olical/aniseed/blob/7bc09736f3651c10d29b82d1a465b7f540614be1/fnl/aniseed/macros.fnl#L188C45-L188C45), but I couldn't figure out where the definition for `sym` is coming from, so I just got stuck here.

I really love the library btw! I think this sort of thing is the right kind of approach to repl-driven development, especially since it lets you add custom clients. If I can get the nodejs repl working, I think it's not that hard to create a netrepl sort of thing where it can also eval into any context, browser, cordova, over the network, etc, by proxying to a websocket.

**Comment by Olical** [comment]
Ah I see! So let's demystify it a little, these blocks are all identical at runtime:

```fennel
(module my-thing)
(def comment-prefix ";; ")
```

```fennel
(local module {})
(tset module "comment-prefix" ";; ")
```

```fennel
{:comment-prefix ";; "}
```

The `def` / `defn` macros just make the Lua module system look prettier and make it so you don't have to jump around the file to see if something is exported or not basically. Sorry that it makes it confusing to follow, it's simpler than it seems at runtime but the macro is pretty terrifying to make that happen.

**Comment by Olical** [comment]
I'm going to close this one because I _think_ there's enough information to unblock, but please re-open if you have any questions! Aniseed->nfnl conversion (which is just plain fennel, no magic macros) is the next big change I'll make to Conjure after [clojure-dap](https://github.com/Olical/clojure-dap) is in a nice spot.

**Comment by Risto-Stevcev** [comment]
Thanks for the help, that worked -- I think just exporting `comment-prefix` fixed that error. I did start making some progress, but I got stuck with something with node I think, because I could get a send/receive sort of thing with a linux pipe but node wasn't sending anything back. I don't think I should be blocked anymore. I'll play around with it some more to see if I can get a minimal debug-able example working as a template.
