### ISSUE TITLE
Duplicate kondo messages with Lazy and your provided config

### ISSUE THREAD

**Issue by TimoKramer** [Olical/conjure#535]
Hi,
when I was switching to [kickstart](https://github.com/nvim-lua/kickstart.nvim) I saw duplicate kondo messages in my clojure-buffers. I copied over the Lazy-config from your README:
```
    config = function(_, opts)
        require("conjure.main").main()
        require("conjure.mapping")["on-filetype"]()
    end,
```
This somehow seemed to trigger a duplicate lsp-instance and I was having duplicate messages.

Just wanted to let you know. Feel free to close this. Maybe a future me will benefit from this here.

**Comment by Olical** [comment]
Huh, well that's weird, Conjure has nothing to do with LSP or clj-kondo, it never invokes either of them 🤔  I suspect something else is at play here.

**Comment by TimoKramer** [comment]
weird, maybe this mason thing is doing something crazy. will need to investigate. without invoking `conjure.main` Conjure is obviously not starting.

**Comment by TimoKramer** [comment]
The only thing I can say is that it's got to do with Conjure. As soon as I comment out conjure it's working fine but commenting out anything else in my clojure-setup is not helping. It's also working with lua and python lsps. 🤷

**Comment by TimoKramer** [comment]
Closing this because the underlying problem is that a lsp-instance in nvim is spawned for the repl-buffer automatically that is created when opening a clj-file. That leads to two lsp-instances that produce duplicate messages. Don't know yet how to solve it but it's not a problem with conjure.

**Comment by Olical** [comment]
Hmmm that's really odd though and I'm sorry you're having to deal with it! Maybe Conjure is triggering the filetype autocmd a second time somehow? Although I don't really see how, it wouldn't be intentional. We _rely_ on the filetype autocmd (probably in the same way as LSP), so I don't see how we'd be able to trigger that multiple times 🤔 

If I understand what you're saying correctly, you mean that the REPL buffer spawns a second LSP that conflicts with the main one you're using for a file, so you have two LSPs linting one file? In that case, I wonder if there's a race condition in how Neovim's LSPs start (either built in, or introduced through how it's configured) that can only manifest on some machines and setups.

**Comment by TimoKramer** [comment]
FYI It just went away. No idea what the problem was but it's gone ¯\_(ツ)_/¯
