### ISSUE TITLE
[Clojure]: A way to configure a default namespace

### ISSUE THREAD

**Issue by bloznelis** [Olical/conjure#539]
Hey, I've been tinkering with Clojure lately, specifically [babashka](https://github.com/babashka/babashka). And babashka comes with some _batteries_ (csv, json, http client libraries), but all of those are under `user` namespace, while default Conjure namespace that gets set when auto-starting babashka REPL is `conjure.internal`.

So question is there a way to replace default `conjure.internal` with other namespace on load?

**Comment by Olical** [comment]
Oh interesting! So there's no way right now but we probably should have one. Or better yet, Conjure can do it's setup stuff in `conjure.internal` then swap you back to the `user` namespace when it's done. I don't know if it needs to be configurable, but it should probably default to user if you don't specify a namespace.

If you put `(ns user)` at the top of your file then it'll probably do the right thing but you might get linting errors. Or maybe use `in-ns` at the top of the file. I think this issue never manifests in JVM Clojure land because everyone has a `ns` form at the top of the file which isn't always the case in bb land which is why the `conjure.internal` startup namespace is carrying over.

**Comment by bloznelis** [comment]
> I don't know if it needs to be configurable, but it should probably default to user if you don't specify a namespace.

Yeah, this also makes sense.

> If you put (ns user) at the top of your file then it'll probably do the right thing but you might get linting errors.

That's the current workaround, yes. But defaulting to `user` would allow users to omit the explicit namespace definition.

**Comment by Olical** [comment]
Pushed a change to develop so the default namespace will be user in Clojure land instead of falling through to whatever nREPL decides. This happened to be the last `ns` / `in-ns` to have been run which was Conjure's bootstrap namespace we send to set up the pretty printing function.

So it wasn't that Conjure was explicitly setting the namespace to `conjure.internal`, it just wasn't specifying _anything_ when you evaluated and the last `ns` to be defined was `conjure.internal` earlier on in the connection. We now never let a `nil` namespace let the nREPL fall through. I worry that this will cause issues...

**Comment by Olical** [comment]
I have a better idea! I'm going to let the nREPL fall through to whatever namespace your repl is in (so that you can use in-ns to change the state within Conjure) BUT I'm going to make Conjure change the namespace away from `conjure.internal` when it's done setting up. You keep the stateful powers but get to fall through to `user` if you don't care. Win win!

**Comment by Olical** [comment]
Done, let me know what you think!
