### ISSUE TITLE
Enhancement: Toggle Quick Doc using key map

### ISSUE THREAD

**Issue by rafaeldelboni** [Olical/conjure#56]
I personally don't like the `quickdoc` showing up all time, but would nice to have a way to show it using some key mapping or when I try to get the doc of a function that doesn't have one.

**Comment by Olical** [comment]
So you can kind of bypass all of the existing mechanisms by mapping a key to `call conjure#notify("quick_doc")`, that will get it displaying when you want it. To clear it you'll have to map something to `ConjureClearVirtual`.

Rather than adding a new mapping this probably requires a little thought around how virtual text (and quick doc) should work. Right now the clearing of virtual text is dependant on quick doc settings which is far from ideal.

I have a backlog entry in my trello to address this and rethink how this passive information works. I'll keep thinking on it, I really want to push for a well documented and stable `v1.0.0` over the next week or so though.

I have next week off in between jobs and I'm hoping to cut an initial "stable" release :D

**Comment by rafaeldelboni** [comment]
Hey thanks for your help!

I just solved this with the following in my `.vimrc` file

```
command! -range ConjureQuickDoc call conjure#notify("quick_doc")
au FileType clojure nmap <leader>gd :ConjureQuickDoc<cr>
```

**Comment by Olical** [comment]
Sweet, glad that worked out for you! I'm hoping I can expose enough of the internals that these kind of custom mappings are really easy to set up and use. I will look at replacing some of the quick doc / virtual text plumbing soon-ish though.

Hopefully it'll be a little more predictable and customable when I'm done with it.
