### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by jeaye** [Olical/conjure#57]
This one's kind of out there, but it just occurred to me as I was writing some Markdown notes. In short, *it would be amazing* to have Conjure within Clojure[Script] code blocks in Markdown files. I imagine most of the time I'd just be using the default Conjure connection, but I could certainly still see someone using the Conjure config to connect to their project and then write some docs about how to use it. In a way, this is a sort of interactive documentation for anyone using Clojure within NeoVim.

So, I could be writing some docs and then have an example:

<pre>
We can use `sort-by` to help categorize the severity of these alligators, 
first by pulling out `:a`:

```clojure
(sort-by :a [{:a 5} {:a 3} {:a 1}]) => ({:a 1} {:a 3} {:a 5})
```
</pre>

This may be well outside the scope of Conjure and I'm not exactly *aching* to have it, but I think it's a good wish list item.

**Comment by Olical** [comment]
Now _this_ is a thinker, I'll get back to you soon about this. It'd be a sweet feature! I'm also considering mod / plugin architecture for Conjure and this might be a great fit for that.

Plugins to Conjure would be written in Clojure and have direct access to Conjure's internals via an API namespace to insulate against changes over time. Thanks for the great idea! Maybe others have thoughts about this too?

**Comment by Olical** [comment]
This is actually MUCH more viable with my new implementation! (`develop` branch)

Excited to try and do this some day soon-ish!

**Comment by dharrigan** [comment]
Would you also support asciidoc as well?

**Comment by rafamedina** [comment]
@Olical Is there API documentation?

**Comment by Olical** [comment]
@rafamedina not yet but that's a good idea! I've documented the API your module needs to exposed to be a valid language client Conjure can hook into, but not the kind of plugin functions.

So there's two extension systems really:

 * A language client which must adhere to an interface of functions and values. Conjure calls into it.
 * A plugin of your own design which calls into functions Conjure exposes.

I was considering creating a module like `conjure.api` that wrapped a bunch of things and would be more resilient to change, but I fear that'll become a huge mess of functions. I think instead I'll write up some help in `:help conjure-api` that describes a bunch of stable, useful and public functions you can hook into as a plugin author.

This will allow you to piggieback on a Conjure instance. Then if I can add autocmds you'll be able to hook into useful events too!

I'll add "document a public API" to my todo list.

**Comment by Olical** [comment]
@dharrigan I mean, why not :D I think anything that lets you describe embedded languages could work.

**Comment by davidsierradz** [comment]
Maybe you can use [chrisbra/NrrwRgn: A Narrow Region Plugin for vim (like Emacs Narrow Region)](https://github.com/chrisbra/NrrwRgn).

vim-pandoc has some code to auto-set the filetype with hooks: [vim-pandoc-after/nrrwrgn.vim at master · vim-pandoc/vim-pandoc-after](https://github.com/vim-pandoc/vim-pandoc-after/blob/master/autoload/pandoc/after/nrrwrgn.vim)

**Comment by Olical** [comment]
Hey! This kinda works now! Just add some config before Conjure loads. If Conjure is already loaded the dict will already be there so you can mutate it rather than replacing it.

```viml
let g:conjure#filetype_client = {"asciidoc": "conjure.client.clojure.nrepl"}
```

You can associate any filetype with any Client, like `"conjure.client.racket.stdio"`. I might close this now since it's totally doable and I know people have used it with books and stuff :D

**Comment by Olical** [comment]
I'm going to close this since it's doable :smile: could do with some blog posts or wiki entries on the general idea and workflow though.

If anyone uses this and writes something up, let me know! I'd love to share it!

**Comment by Olical** [comment]
Oh no, I think this is Neovim's breaking changes... again :( there's been a lot recently. I fixed a breaking change for Neovim 0.7 but I didn't make it backwards compatible because they said it was a deprecation of the old name, so I thought that meant this new name would work in both the older and newer versions.

I'm just guessing here, but I _think_ that's what's happened. So I need to add another gate on the Neovim version and call a different function. If you turn off Conjure's tree sitter support for now (which is on by default at the moment, see `:h conjure`) it should be fine? And I had to turn on treesitter support by default to work around a Neovim issue someone else was having 😬

Half the issues and work right now is just to workaround how Neovim 0.5, 6, 7 all seem to have their own subtle breaking changes and quirks. And everyone tends to use different versions and lag behind the latest release... makes support quite tricky!

**Comment by Olical** [comment]
Of course it could be something entirely unrelated to this and I'll need to look when I have some free time. But that's my hunch and suggested workaround _for now_.

**Comment by Olical** [comment]
The error itself is actually coming from inside the tree-sitter library, not my code, but the way I'm calling it might not be helping.

**Comment by stevenproctor** [comment]
Updating to NeoVim 0.7.0 seems to have resolved this.  Thanks.
