### ISSUE TITLE
Conjure throws error new Buffer

### ISSUE THREAD

**Issue by mo-shaz** [Olical/conjure#582]
## Summary
From today, when opening any CLJ file, Conjure seems to throw the following error. But, there seems to be no update from Conjure since the last two weeks and I haven't made any major changes to my config.

![image](https://github.com/Olical/conjure/assets/81179191/ad91831c-41f4-4714-9901-c5dc1bf5aaa8)

Only issue is this error on the new buffer, everything else seems to work fine.

## Steps to reproduce
1. open Neovim
2. open any `.clj` file

**Comment by Olical** [comment]
Sorry about the issue! Could you share which Neovim version you're using
and the full error which should be visible in your notifications or
messages. That screenshot is cutting off the right hand side of the first
line which I think is where the failing function is actually listed.

The rest of that error is the stack above the failure which doesn't narrow
it down too much.

I released changes yesterday (see release notes for the full list) which
included turning off diagnostics in the log buffer since I had so many
people asking how they could remove them, so I made it part of the
configuration.

My guess is that the LSP method I'm calling either doesn't exist in your
Neovim version (they change method names quite a lot which I keep on top of
but sometimes miss backwards compatibility with old method names in older
Neovim versions) or you've disabled something that I thought always existed.

Either way, I think I need to wrap one of my new function calls in a guard
to prevent some users from seeing this error.

The changes had been used by a few people on the develop branch including
myself for a couple of weeks so it must be something slightly rare 🤔

Do you use LSP and diagnostics normally? Or tree sitter?

**Comment by mo-shaz** [comment]
Sorry for the bad screenshot and late response 😬 

- Nvim Version:
```yml
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

- Complete error:
```bash
Error executing vim.schedule lua callback: ...az/.local/share/nvim/lazy/conjure/lua/conjure/buffer.lua:44: ...5/nvim-linux64/share/nvim/runtime/lua/vim/diagnostic.lua:1574: bufnr: expected number, got boolean
stack traceback:
	[C]: in function 'new_buf_fn'
	...az/.local/share/nvim/lazy/conjure/lua/conjure/buffer.lua:44: in function 'upsert_buf'
	...-shaz/.local/share/nvim/lazy/conjure/lua/conjure/log.lua:339: in function 'append'
	...lazy/conjure/lua/conjure/client/clojure/nrepl/action.lua:108: in function <...lazy/conjure/lua/conjure/client/clojure/nrepl/action.lua:55>
```
- Response:
> Do you use LSP and diagnostics normally? Or tree sitter?

I do use LSP and diagnostics which is installed via Mason. But I think Treesitter is also configured and running. I really have no clear idea how these things work 😅

**Comment by practicalli-johnny** [comment]
I **cannot** replicate this issue myself, using the latest conjure on master with Neovim 0.10.0.  There may be some API changes between 0.9.x and 0.10.0 that cause the issue.

> I will do a test using Termux as that only has Neovim 0.9.5

I opend Neovim with a README.md from a Clojure project and then opened a `*.clj` file from the project.

```
    ● conjure 18.48ms  clojure
        dir     /Users/johnny/.local/share/nvim-astro/lazy/conjure
        url     https://github.com/Olical/conjure
        version 4.52.0
        tag     v4.52.0
        branch  master
        commit  9346878
```

I am using AstroNvim 4 with the [Practicalli Astro configuration](https://github.com/practicalli/astro) which uses Lazy package manager.  
This config includes Clojure LSP installed by Mason.  
nvim-treesitter is part of the configuration along with nvim-treesitter-sexp plugin and the Treesitter parser for Clojure. 

Tested using Neovim 0.10.0 release on Linux and MacOSX.
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

**Comment by practicalli-johnny** [comment]
I can replicate the issue in part on Neovim 0.9.5 on Termux (linux-android). The Clojure file does open correctly, but the LSP server seems to fail.

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1716656478

```lua
│Error executing vim.schedule lua callback: ...ocal/share/astro││stack traceback:                                              ││  [C]: in function 'new_buf_fn'                               │
│  ...ocal/share/astronvim/lazy/conjure/lua/conjure/buffer.lua:│
│  .../.local/share/astronvim/lazy/conjure/lua/conjure/log.lua:│
│  ...lazy/conjure/lua/conjure/client/clojure/nrepl/server.lua:│
│  vim/_editor.lua:263: in function <vim/_editor.lua:262>
```

**Comment by Akeboshiwind** [comment]
I'm pretty sure this is a problem due to a breaking change in [nvim 0.10](https://neovim.io/doc/user/news-0.10.html) for the signature of `vim.diagnostic.enable`.

The signature seems to have changed from: `enable({bufnr}, {namespace})` to `enable({enable}, {filter})`.

Conjure uses the [new signature](https://github.com/Olical/conjure/blob/934687860a71d1d03e569ce11f880a4d404e69aa/fnl/conjure/log.fnl#L44) which is incompatible with the old signature that 0.9 and below use.

**Comment by mo-shaz** [comment]
> I'm pretty sure this is a problem due to a breaking change in [nvim 0.10](https://neovim.io/doc/user/news-0.10.html) for the signature of `vim.diagnostic.enable`.
> 
> The signature seems to have changed from: `enable({bufnr}, {namespace})` to `enable({enable}, {filter})`.
> 
> Conjure uses the [new signature](https://github.com/Olical/conjure/blob/934687860a71d1d03e569ce11f880a4d404e69aa/fnl/conjure/log.fnl#L44) which is incompatible with the old signature that 0.9 and below use.

Yes, it is. I updated my NVIM version to 0.10.0 and no more errors. Thanks for the quick resolution @Akeboshiwind @practicalli-johnny @Olical 🚀 ❤️

**Comment by Olical** [comment]
Going to reopen this for now because really we should support older versions for a while at least. I should've caught this one already and I'm surprised my test suite didn't! It runs it under older versions to catch things like this. Or it should be...

**Comment by Olical** [comment]
Pushed a change to develop that adds

```fennel
    (if (= 1 (vim.fn.has "nvim-0.10"))
      (vim.diagnostic.enable false {:bufnr buf})
      (vim.diagnostic.disable buf)))
```

Looks a bit awkward but does the trick.

**Comment by Olical** [comment]
If someone on Neovim < 0.10 can confirm this too, I'll mark this as complete and release it. It works fine for me now but a 3rd party too would be great!

**Comment by mo-shaz** [comment]
> If someone on Neovim < 0.10 can confirm this too, I'll mark this as complete and release it. It works fine for me now but a 3rd party too would be great!

I can test it out via `bob.nvim` manager 😁 
Should I explicitly mention the branch in Lazy config?

**Comment by Olical** [comment]
Yep, you'll have to swap to the develop branch with your plugin manager.

**Comment by mo-shaz** [comment]
> Yep, you'll have to swap to the develop branch with your plugin manager.

I can confirm it works NVIM version < 0.10.0 now.
![image](https://github.com/Olical/conjure/assets/81179191/668fcb8e-f8f8-466a-9de5-0f8ab5f9a93d)

Nvim Version tested:
```yml
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```
