### ISSUE TITLE
Recognize `.bb` extension as Clojure

### ISSUE THREAD

**Issue by sarna** [Olical/conjure#609]
Hi!

Would it be possible to recognize `.bb` files (Babashka scripts) as Clojure? For now Conjure doesn't know anything about them, and I don't see a `g:conjure#filetype_suffixes#clojure`.

**Comment by russtoku** [comment]
You can set up an autocommand that will recognize the filename extension, `.bb`, as a Clojure file.

At the Neovim command line, run:
```
aug my_bb | au! | autocmd my_bb BufNewFile,BufRead *.bb setlocal filetype=clojure
```
This will confirm that the above command did work correctly:
```
:au my_bb                                                                                              
--- Autocommands ---
my_bb  BufNewFile
    *.bb      setlocal filetype=clojure
my_bb  BufReadPost
    *.bb      setlocal filetype=clojure
```

**Comment by Olical** [comment]
A neat fix @russtoku! Thanks! There's this open issue on clojure.vim too https://github.com/clojure-vim/clojure.vim/issues/38 which I think would be a great place to fix this.

Hopefully we'll see official support in the language plugin some day soon! Maybe we need to contribute it though?

Will close this for now since I think this is a good answer and I don't think Conjure should be controlling your extension to filetype mappings, that could get messy.
