### ISSUE TITLE
squint-cljs nrepl eval file failing

### ISSUE THREAD

**Issue by diegobfernandez** [Olical/conjure#613]
Hello there. I've been experimenting with [squint-cljs](https://github.com/squint-cljs/squint) and everything is working well expect the evaluation of the whole file.

Here is the output when pressing `<localleader>ef`
```
; eval (file): /project/src/project/main.cljs
; (err) undefined is not an object (evaluating 'globalThis.project.main.cljs.core')
```

If I understand correctly this is the code that will eventually send the nrepl message to the server
https://github.com/Olical/conjure/blob/6d2bc7f7b24c2c43d54f263bee7b9b08aef5d1a1/fnl/conjure/client/clojure/nrepl/action.fnl#L241-L243

The problem is that squint-cljs is not ClojureScript :sweat_smile: and does not ship with `cljs/clojure` namespaces.

The solution could be another client, but since all other evaluation methods are working, I wonder if using nREPL's [`load-file`](https://nrepl.org/nrepl/ops.html#load-file) could be a solution that works for all nREPL clojure-like languages.

**Comment by Olical** [comment]
Thanks for the report! If squint has it's own reader conditional key then we could use that but if not maybe we need to make the `:cljs` branch a little more delicate so it detects if we're in a squint environment or not and behaves differently.

I'll try to look at this soon!

**Comment by Olical** [comment]
Looking into this some more now and squint doesn't seem to have any sort of equivalent for `load-file`, so I don't think Conjure's file loading mapping can be used with it at all really. Unless you make some assumptions about the runtime you're executing your compiled Squint JS in, like if it's nodejs maybe we can access the filesystem.

I think you'll need to use `<prefix>eb` which sends the current buffer contents directly instead of relying on the REPL having access to the file system.

**Comment by diegobfernandez** [comment]
Thank @Olical, for the time being I've been using `<prefix>eb` indeed. I'll probably override my eval file key mappings for squint projects to aleviate the muscle memory effect.
 
I still wonder if the `load-file` op could be a good fit as it seems that the code is sent as part of the message, so no assumptions about runtime as the client will be responsible for reading from disk.

**Comment by Olical** [comment]
Hmm does squits REPL support that op too? 🤔 if so, we could use that. Not sure about changing the underlying op in Conjure though. This fees like it'll actually be useful for eval buffer.

Right now we ask the REPL to load the file from disk, that way if you're working on a remote machine you get the file from that remote host. You don't need it on your local host where Neovim lives.

If we went down the load-file route for Conjure for eval buffer _and_ file we could do the same op for both but eval file reads the contents from disk and eval buffer reads from the currently loaded buffer inside Neovim.

If both work very well, in more scenarios _and_ don't break anyone's workflow / environment it could be a nice change.

**Comment by Olical** [comment]
I think I also designed `,ef` so that if your file was say 100k lines of data you could have the REPL read it directly rather than Neovim read it and cram it into an nREPL message. So it might make sense to keep `,ef` with that "Neovim never sends the full contents directly" behaviour, I'm not too sure. Although that situation will be extremely rare and there's other ways around that...

**Comment by Olical** [comment]
I've implemented the `load-file` nREPL op as the backend for "eval file" within Clojure buffers. Let me know how this works for you now @diegobfernandez - hopefully it'll work great! It works with babashka, cljs and clj for me although I haven't tried squint since I'm writing this on a train and just about had enough time to get this part done before a change of trains.

Something to consider is maybe we want to send the current buffer contents instead of reading the file from disk. So `eb` would send the buffer contents over eval, `eb` reads the file from disk using Neovim APIs then sends it to the `load-file` operation.

The previous behaviour is that the file reading would happen inside the REPL itself, so if you were REPLed into a remote machine you could use `ef` to load the file from the remote hosts disk. I have a feeling that isn't actually useful 99.9% of the time so reading from the host machine is probably a good move.

This final question though of "should we ever actually read from disk" is interesting though, what's the least surprising thing for the user? I kinda feel like what we have now is best, `eb` is buffer contents, `ef` is from host machine disk. So I'll probably leave it like that but if you have any thoughts or ideas let me know!

If this works for you in squint-cljs, please do close this issue 😄

**Comment by diegobfernandez** [comment]
oh! so nice. I wasn't expecting this.
I've tested in squint-cljs and there are no errors now.
although I've just realised (looking at squint's nrepl implementation) that `load-file` is commented out, so no actual eval is happening.

Thanks for taking my issue into consideration.
