### ISSUE TITLE
Add support for Joker Socker Repl

### ISSUE THREAD

**Issue by gleisonsilva** [Olical/conjure#70]
I'd love to see support for connecting to a Joker repl. It supports Socker Repl, I've tried connect to it, but I couldn't find a way. When I call :ConjureUp it shows "Adding :dev" but don't go beyond that.

To be able to run those tests I also have to rename my script-file.joke to script-file.clj so that Conjure recognizes it.

**Comment by Olical** [comment]
This requires two things to work I'm afraid. Joker needs to support the socket prepl, not just a REPL. The prepl is an agreement of how each response from the repl will be wrapped in edn data. The joker author could use my post to work out how: https://oli.me.uk/clojure-prepl-for-tool-authors/

Secondly, Conjure assumes it can use everything Clojure has to offer to make evaluations work correctly. Conjure would require a new `:lang` config for joker that turned some things off. A bit like when you set it to `:lang :cljs`.

First steps would be opening an issue with joker about prepl.

**Comment by Olical** [comment]
I'm going to close this since there's nothing for Conjure to do, Joker needs to add prepl support, maybe open an issue there with a link to my article and register your interest?

If you post it in the Conjure channel on the Clojurians Slack you could get more people to join in too, if everyone is interested in a prepl I'm sure it would get implemented, it could even be contributed by someone in #conjure that quite likes Go (not me though :grimacing: I never liked it).

**Comment by Olical** [comment]
Ah, okay, it would require a tiny bit of work, since you'd have to set a new `:lang`, but that's another issue really.
