### ISSUE TITLE
Sorted sets are pretty printed in arbitrary order

### ISSUE THREAD

**Issue by franciscod** [Olical/conjure#73]
This is really weird. How can I help diagnose this?

![image](https://user-images.githubusercontent.com/726447/70599955-3fbfc700-1bcd-11ea-8f60-a27988ed7ab9.png)

Wrapping the thing with `println` and running the file via `clj` works as expected.
```
$ clj wtf.clj
#{1 2 4 5 6 7 8}
```

**Comment by Olical** [comment]
I understand this issue and will explain soon. It's too do with reparsing
the result for pretty printing losing the sorted info since the text
representation of sorted and unsorted sets is the same, I think?

**Comment by Olical** [comment]
I can assure you it _is_ a sorted set, it's just being unsorted when Conjure parses the output from the prepl so that it can pretty print it. `(sorted-set 3 2 1)` returns `#{1 2 3}` which Conjure will then parse as Clojure data from the string the prepl returned.

This results in an _unsorted_ regular set of `#{2 1 3}` (order undefined). This is purely for pretty printing, the solution would be to move pretty printing down into the JVM / JS env hosting the prepl so that it returns an already formatted string which maintains sorting. This is something I may address in a drastic rewrite of some underlying mechanisms of Conjure.

Sadly, I don't think I can fix this right now since the string representation of a sorted-set is identical to an unsorted set :sob: I promise the value _is_ a sorted set, it just loses the sorting when displayed in Conjure. If you `pr-str` it or print it yourself it'll display with sorting.

**Comment by franciscod** [comment]
Ah, it being an issue with the pretty printing seems a bit less worrying. Thanks for the detailed explanation! I guess this issue could remain open as a heads up for the next time it comes up / tracking the "move the pretty printing down" task, but feel free to close it up as you will :)

**Comment by franciscod** [comment]
Humble hint from a total newbie: maybe you can skip pretty-printing for `PersistentTreeSet`s?

```
user=> #{1 2 3 4 5}
#{1 4 3 2 5}
user=> (type *1)
clojure.lang.PersistentHashSet
user=> (sorted-set-by < 1 2 3 4 5)
#{1 2 3 4 5}
user=> (type *1)
clojure.lang.PersistentTreeSet
```

**Comment by Olical** [comment]
Decent idea! I'll take a look soon :smile: I'll leave the issue open though, definitely useful.

**Comment by Olical** [comment]
I've taken the liberty to change the title to something that kind of explains the issue, just for those skimming the issue list etc. I hope that's okay!

**Comment by Olical** [comment]
The `develop` branch is now usable and doesn't have this issue (among many others!) I highly recommend you check it out :smile: kind of fixed bugs by completely rewriting the project. May be closable since I'm deprecating the old JVM implementation.

**Comment by Olical** [comment]
![image](https://user-images.githubusercontent.com/315229/80815424-88503f00-8bc5-11ea-8501-c973422b2400.png)

**Comment by franciscod** [comment]
Nice! Thanks!
