### ISSUE TITLE
ClojureScript Completion?

### ISSUE THREAD

**Issue by smolck** [Olical/conjure#75]
Hello! I've been looking around this and Compliment's repo (like alexander-yakushev/compliment#62) and I'm not sure if ClojureScript autocompletion is possible or what left needs to be done for it to work, if anything. That PR I linked seems to indicate that autocompletion can work now, but https://github.com/clojure-emacs/cider-nrepl/issues/634#issuecomment-522145442 makes me think that isn't the case. Would you mind giving an update on ClojureScript autocompletion? I.e. what's blocking progress in this area?

Thanks in advance! This project is *really* great for ClojureScript (and Clojure!) development, but when using it I miss the autocompletion provided in [Calva](https://github.com/BetterThanTomorrow/calva) (VSCode), and so would really like to see that sort of autocompletion in Conjure.

**Comment by Olical** [comment]
Hey! So I haven't had a delve into the world of CLJS completion for a while since I've been working on tangential projects to Conjure (that will help me make Conjure better in the future). I honestly don't know if it's possible right now, I was under the impression that it required some special nREPL stuff to work with Complement.

I was told that https://github.com/rksm/clj-suitable should work these days but again, I haven't had a go with it in a prepl yet, just a matter of having the time to try it. If suitable works fine in a CLJS prepl then there's no reason why we can't hook it up, shouldn't be hard at all since I think it has the same API!

I might check it out soon, but if you have some working CLJS completion somewhere in a prepl and can prove it I'll be more than happy to help integrate it :smile: I'll have a quick poke now although I can't promise anything.

**Comment by Olical** [comment]
Looks like suitable also requires access to the ClojureScript compiler to work, this means changing the ClojureScript prepl to expose an eval function of some kind which would be _really_ useful but would mean patches to core. I think...

**Comment by smolck** [comment]
Thanks for the quick reply! So you think for completion Suitable is the most likely to work (and work well)?

Also, anything I can do to help out? I'm happy to do so wherever I can.

**Comment by Olical** [comment]
Hmm, suitable looks like it _could_ be good but I'd need access to an `eval` function within the ClojureScript prepl, which I don't think exists right now? If I can find a way to expose an `eval` that calls through to the compiler it'll all work fine, until then I'm kinda stuck with CLJS completion.

The nREPL stuff adds some middleware to enable this sort of thing I think? Something similar for prepl would be ideal, I think I'd need to go chat with the devs on the Slack.

**Comment by smolck** [comment]
Actually, there is an `eval` function. From running `(doc eval)` in a prepl started with `clj -Sdeps '{:deps {olical/propel {:mvn/version "1.3.0"}}}' -m propel.main`:
```
clojure.core/eval
([form])
  Evaluates the form data structure (not text!) and returns the result.
nil
```

Is that what you're looking for?

**Comment by smolck** [comment]
@Olical There is an `eval` function:
```
-------------------------
cljs.core/eval
([form])
  Evaluates the form data structure (not text!) and returns the result.
  Delegates to cljs.core/*eval*. Intended for use in self-hosted ClojureScript,
  which sets up an implementation of cljs.core/*eval* for that environment.

nil
```

Is that what you want? (Output from `(doc eval)` in a prepl started with `clj -Sdeps '{:deps {olical/propel {:mvn/version "1.3.0"}}}' -m propel.main --env node`)

**Comment by Olical** [comment]
Nope, not quite I'm afraid. That relies on *eval* being bound which it
isn't by default. So you either need to set up self hosted cljs (which
might work!) or have the repl environment the prepl sets up bind *eval* to
it's internal compiler somehow.

I think it needs to be from the prepl since you want to get all of the
dependency information from the outer context. Self hosted cljs starts as a
blank slate (I think???) which wouldn't be very useful for completion.

I just need to go ask the ClojureScript channel on slack about this really.

**Comment by smolck** [comment]
> So you either need to set up self hosted cljs (which might work!)

After setting up self hosted cljs, what do I need to do next to test that the `eval` function is working as needed (or what to do for testing suitable completion)?

> I just need to go ask the ClojureScript channel on slack about this really.

Okay, sounds good. Hopefully the solution’s fairly easy to implement ;)

**Comment by bbatsov** [comment]
> Hello! I've been looking around this and Compliment's repo (like alexander-yakushev/compliment#62) and I'm not sure if ClojureScript autocompletion is possible or what left needs to be done for it to work, if anything. That PR I linked seems to indicate that autocompletion can work now, but clojure-emacs/cider-nrepl#634 (comment) makes me think that isn't the case. Would you mind giving an update on ClojureScript autocompletion? I.e. what's blocking progress in this area?

Just a small note - the work in Compliment was actually reverted in the end in favour of `clj-suitable`. It now provides a couple of completion sources for compliment for dynamic (eval-based) and static ClojureScript completion. And yes - this functionality is independent of nREPL, but you'll definitely need the ClojureScript compiler environment to leverage it.

**Comment by smolck** [comment]
> Just a small note - the work in Compliment was actually reverted in the end in favour of clj-suitable

Thanks for the info! So does clj-suitable effectively make Compliment obsolete then?

> but you'll definitely need the ClojureScript compiler environment to leverage it.

Could this be done by using CIDER middleware in the prepl (since CIDER uses clj-suitable by default)? Alternatively, as @Olical stated above, self-hosted cljs might work? I'd like to test this, but I'm not sure exactly how; any pointers would be much appreciated!

**Comment by bbatsov** [comment]
> Thanks for the info! So does clj-suitable effectively make Compliment obsolete then?

Depends on your perspective - it's meant to be used as a compliment plugin (source), but you can also use it standalone if you wish. compliment is definitely the best completion library for Clojure and provides a great API for extending its completion capabilities. 

> Could access to the cljs compiler be obtained through CIDER middleware loaded in the prepl (since CIDER uses clj-suitable by default)? Alternatively, as @Olical stated above, self-hosted cljs might work? I'd like to test this, but I'm not sure exactly how; any pointers would be much appreciated!

You can't use `cider-nrepl` without nREPL, but you can use the orchard library - which does the actual manipulation of the cljs compiler's environment. Not sure how easy it is to get this data under prepl, but I expect it's not rocket science.

**Comment by smolck** [comment]
> you can use the orchard library . . . . I expect it’s not rocket science.

Thanks! From their README’s [`REPL Agnostic` section](https://github.com/clojure-emacs/orchard#repl-agnostic):

> No matter whether you're using nREPL, a socket REPL, unrepl or prepl, Orchard has your back. nREPL clients might opt to wrap some of the Orchard functionality in middleware for convenience (as cider-nrepl does), but they can just eval away if they please.

So maybe it might “just work”? I’ll see if I can get this working in the prepl; thanks for pointing me in the right direction!

**Comment by smolck** [comment]
Hmm, it's simple to use orchard in a non-cljs prepl, just using `clj -Sdeps '{:deps {olical/propel {:mvn/version "1.3.0"} cider/orchard {:mvn/version "0.5.6"}}}' -m propel.main`. 

The hard part seems to be getting this to work with `--env node` (assuming it's supposed to?). When trying to `(require '[orchard.cljs.analysis])`, for example, the prepl just complains that it can't find `misc.cljs` or `misc.cljc`, which makes sense since [that's a clojure file](https://github.com/clojure-emacs/orchard/blob/master/src/orchard/misc.clj). Not exactly sure what's happening there.

**Comment by Olical** [comment]
As far as I'm aware, the ClojureScript prepl as it stands doesn't give you access to the compiler or REPL environment in any way which is reaaaaaly limiting (which is why I haven't been able to do much with CLJS other than basic eval). I think I need to go ask dnolan etc on #clojurescript but I'm just working on some other things at the moment.

**Comment by Olical** [comment]
I think you _need_ access to the outer environment to make any of this tooling remotely viable. Maybe the best thing to do would be to sort of copy / paste the current prepl implementation into a lib where I can fix all the issues I found with it (waiting for more patches to be merged atm, I think it's been more than a year?).

That way I could have canonical prepl accept functions that are unified across Clojure and ClojureScript that could _hopefully_ be completely patched back into core since they still fit the same ethos of the original.

It's just annoying that we need a dep to use a thing that is supposed to be core, but it would be a very small one. I'll have a play with this concept alongside my Conjure rewrite.

**Comment by bbatsov** [comment]
> (waiting for more patches to be merged atm, I think it's been more than a year?).

That's why I hate depending on core functionality - it's super hard to get any changes in there. For some patches I waited several years. :D

**Comment by Olical** [comment]
Yeaaah, I'm feeling that. Some got merged which is great but I'd like it to move a little faster since a lot of them are basically one liners. I think my enabling of reader conditionals in Clojure prepls got delayed to 1.11? So yeah, I think I'll work on Propel a little more to add custom accept fns that fix a bunch of issues.

I guess having access to the compiler env + eval will be morrre than enough.

**Comment by Olical** [comment]
The `develop` branch is now usable and doesn't have this issue (among many others!) I highly recommend you check it out :smile: kind of fixed bugs by completely rewriting the project. May be closable since I'm deprecating the old JVM implementation.

ClojureScript completion is working with Conjure (`develop`) + `shadow-cljs` over nREPL :tada:

**Comment by smolck** [comment]
Awesome! Haven’t been doing cljs development recently, but I think I’ll try this out! Thanks!
