### ISSUE TITLE
syntax source for asyncomplete.vim via conjure

### ISSUE THREAD

**Issue by thecontinium** [Olical/conjure#76]
Hi 

I've implemented a conjure autocompletion [source](https://github.com/thecontinium/asyncomplete-conjure.vim/blob/master/autoload/asyncomplete/sources/conjure.vim) for [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim)

It seems to work but I'm not entirely sure if I've used the conjure interface correctly ?

I'm also not sure what is the best keyword regex to use in the matchstr function; it's currently using '\w\+$'.

If you could take a look that would be great.

Any advice welcome.

Cheers

**Comment by Olical** [comment]
This seems cool! That call seems okay to me although it'll be blocking since it's in vim script :cry: I'm guessing you want it to be async since you're building it for asyncomplete?

If you have a look at Conjure's built in deoplete source: https://github.com/Olical/conjure/blob/d3356a4de488a2e2791d06c8ff3d1e193e94e685/src/rplugin/python3/deoplete/sources/conjure.py

You can see that it's doing the same as you but it's doing it from a separate Python process which won't lock up Neovim. Does asyncomplete somehow avoid this despite being Vim Script?

I feel like if you want to do async completion from pure Neovim you need to send an async call and then get some sort of callback from Conjure, something that isn't implemented right now.

I'm not too sure about the regex but this is the one I'm using with deoplete, maybe it'll be helpful?

```vim
call deoplete#custom#option('keyword_patterns', {'clojure': '[\w!$%&*+/:<=>?@\^_~\-\.#]*'})
```

So yeah, the call you're making looks good, but it'll be blocking because it's an RPC request which needs to wait for a response.

**Comment by thecontinium** [comment]
asynccomplete suggests [this](https://github.com/prabirshrestha/asyncomplete.vim#using-existing-vim-plugin-sources) interface

**Comment by Olical** [comment]
This is working well, I tested it myself :D thanks!
