### ISSUE TITLE
"eval root" only appears to work for S-expressions

### ISSUE THREAD

**Issue by daveyarwood** [Olical/conjure#87]
If I put my cursor inside of a top-level expression like:

```clojure
(+ 2 3)
```

And press `<localleader>er`, the result is 5.

However, if I do the same thing for a top-level expression like:

```clojure
{:a 2, :b 3, :c (+ 4 5)}
```

then nothing happens.

It looks like this might be by design, based on the help text:

```
<localleader>er          Evaluate the root form under the cursor. This is the
                         outermost pair of parenthesis. Great for evaluating a
                         function you're editing if your cursor is within a
                         few nested forms.
```

But it did trip me up just now, on this one rare occasion when I wanted to eval a map at the top level by using the convenient  `<localleader>er` mapping.

Is it possible to teach the "eval root" logic to look for curly braces / square brackets in addition to parentheses?

**Comment by Olical** [comment]
So this was by design originally, I basically define "form" as pair of parens. Without this restriction it makes evaluating specific forms a little tricky when you have maps and vectors dotted around.

Having `,ee` evaluate the parens under your cursor is usually what you want (in my opinion?). The same kind of goes for `,er` but maybe not so much. I'll give it a ponder, anyone else have thoughts on this?

I can hunt for other kinds of pairs too, but it'll incur a performance hit since I need to scan for all three kinds of pairs. This can get slow on some machines, maybe I can make it configurable.

**Comment by daveyarwood** [comment]
I think it might be reasonable to punt on this until treesitter support in Neovim is mainstream. Hopefully that would make this a lot easier to implement.

Until then, it's really not too annoying to work around. I can just wrap maps in a (do ...) or visually select what I want to eval. 🙂

**Comment by Olical** [comment]
I've pushed a change to develop that adds support for `[]` and `{}` pairs in form searching. It's also configurable! Let me know what you think :smile:

**Comment by daveyarwood** [comment]
I just gave the develop branch a try, works like a charm! Thanks! :100:
