### ISSUE TITLE
Session type appears like ???? 

### ISSUE THREAD

**Issue by adz5a** [Olical/conjure#93]
Hello congratz on your latest release :)

This is not really a bug but I thought i'd report it:
Session type appears like ???? on shadow-cljs nrepl sessions when no applications are connected yet. They appear as "ClojureScript" normally after the application connected.

```
; Sessions (1):
; >1 - Lagotto Romagnolo (???)
; --------------------------------------------------------------------------------
; Sessions (1):
; >1 - Lagotto Romagnolo (ClojureScript)
```

**Comment by Olical** [comment]
Yep, that's intended but thanks for reporting! Not sure if I can do anything about this, I'm sending some code to check the session type and shadow is responding with an error because there's nowhere to evaluate the code yet.

That leaves me with no result when I query the REPL type. I suppose I could add something really specific that checked for shadow-cljs errors like this and set the REPL type to "ClojureScript (no runtime)" or something :thinking:

**Comment by Olical** [comment]
I've tweaked it slightly so it says `no env` instead of `???` now, it's not fully descriptive but it's better. It's on develop for now.
